### ISSUE TITLE
Android some modules throw exceptions

### ISSUE THREAD

**Issue by aurcioli-handy** [n1nj4sec/pupy#171]
Loaded Pupy successfully on an Android 5 device, but no matter what transport I use I keep getting this error:

```
WARNING:PUPY/7777:failed to serve client, caught exception : stream has been closed
WARNING:PUPY/7777:failed to serve client, caught exception : stream has been closed
WARNING:PUPY/7777:failed to serve client, caught exception : stream has been closed
WARNING:PUPY/7777:failed to serve client, caught exception : stream has been closed
WARNING:PUPY/7777:failed to serve client, caught exception : stream has been closed
WARNING:PUPY/7777:failed to serve client, caught exception : stream has been closed
```

**Comment by mrzear** [comment]
@aurcioli-handy So It doesnt work on android then?

**Comment by asyazwan** [comment]
I tried on my Android 6.0.1. Neither the provided APK nor the one I manually build works (API 19). They crashed with:

```
22265 22292 I python  : Android kivy bootstrap done. __name__ is __main__
22265 22292 I python  : Run user program, change dir and execute main.py
22265 22292 I python  :   File "<string>", line 86, in load_module
22265 22292 I python  :   File "<memimport>/network/lib/streams/PupyAsyncStream.py", line 10, in <module>
22265 22292 I python  :   File "/home/pupy/pupy/client/android_sources/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/multiprocessing/__init__.py", line 84, in <module>
22265 22292 I python  : PupyPackageLoader: Error while loading package network.lib.streams.PupyAsyncStream (py) : No module named _multiprocessing
22265 22292 I python  :   File "<string>", line 86, in load_module
22265 22292 I python  :   File "<memimport>/network/lib/streams/__init__.py", line 4, in <module>
22265 22292 I python  :   File "<string>", line 118, in load_module
22265 22292 I python  : PupyPackageLoader: Error while loading package network.lib.streams (py) : No module named _multiprocessing
22265 22292 I python  :   File "<string>", line 99, in load_module
22265 22292 I python  :   File "/home/pupy/pupy/pupy/network/lib/__init__.py", line 1, in <module>
22265 22292 I python  :   File "<string>", line 118, in load_module
22265 22292 I python  : PupyPackageLoader: Error while loading package network.lib (pyc) : No module named _multiprocessing
22265 22292 I python  :   File "<string>", line 86, in load_module
22265 22292 I python  :   File "<memimport>/network/conf.py", line 6, in <module>
22265 22292 I python  :   File "<string>", line 118, in load_module
22265 22292 I python  : PupyPackageLoader: Error while loading package network.conf (py) : No module named _multiprocessing
22265 22292 I python  : Traceback (most recent call last):
22265 22292 I python  :   File "/home/pupy/pupy/client/android_sources/.buildozer/android/app/service/main.py", line 11, in <module>
22265 22292 I python  :   File "/tmp/tmp_pupy_TpLOQk/pp.py", line 1, in <module>
22265 22292 I python  :   File "<string>", line 59, in <module>
22265 22292 I python  :   File "<string>", line 118, in load_module
22265 22292 I python  : ImportError: No module named _multiprocessing
22265 22292 I python  : Python for android ended.
```

At least OP got it to trying to connect. That error is a curious one since Android doesn't support multiprocessing from what I gather. Since I'm not familiar with Kivy/P4A I'm gonna try again later when I have more time to investigate. If you're gonna try to build make sure you're using P4A `old_toolchain` branch.

@aurcioli-handy What Android version and what commands you generated payloads with? I get that error when trying py/win payloads. Seems like launcher configs got messed up because the same payload manually ran with `--host x.x.x.x -t rsa` works.

**Comment by n1nj4sec** [comment]
there is still a problem with pyjnius on android 6.x, the template probably needs an update, I will investigate later

**Comment by asyazwan** [comment]
Yeah, it's working now with the multithread patch. Got it to connect and all, but like you said some modules are still throwing exception. Thanks.
