### ISSUE TITLE
ImportError: No module named genpayload

### ISSUE THREAD

**Issue by bahadirpektas** [n1nj4sec/pupy#19]
I think the file "pupygen.py" in "/pupy" folder should be renamed to "genpayload.py" .

root@kali:/opt/pupy/pupy# ./pupysh.py

            _____                    _       _ _            
 ___ ___   |  _  |_ _ ___ _ _    ___| |_ ___| | |   ___ ___ 
|___|___|  |   __| | | . | | |  |_ -|   | -_| | |  |___|___|
           |__|  |___|  _|_  |  |___|_|_|___|_|_|           
                     |_| |___|                              

                           v1.0.0

>> help
Traceback (most recent call last):
  File "./pupysh.py", line 62, in <module>
    pcmd.cmdloop()
  File "/opt/pupy/pupy/pupylib/PupyCmd.py", line 259, in cmdloop
    cmd.Cmd.cmdloop(self, intro)
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/opt/pupy/pupy/pupylib/PupyCmd.py", line 322, in do_help
    cmds_doc.append((name, self.pupsrv.get_module(self.aliases[name]).__doc__))
  File "/opt/pupy/pupy/pupylib/PupyServer.py", line 210, in get_module
    module=loader.find_module(module_name).load_module(module_name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/opt/pupy/pupy/modules/migrate.py", line 3, in <module>
    import genpayload
ImportError: No module named genpayload

>> exit

**Comment by n1nj4sec** [comment]
oops, forgot dome imports after refactoring, it's fixed thank you
