### ISSUE TITLE
Pupysh.py not working in ubuntu 14.04

### ISSUE THREAD

**Issue by mummyknow** [n1nj4sec/pupy#202]
Traceback (most recent call last):
  File "pupysh.py", line 68, in <module>
    pupyServer=pupylib.PupyServer.PupyServer(args.transport, args.transport_args, port=args.port)
  File "/home/live/Documents/pupy/pupy/pupy/pupylib/PupyServer.py", line 89, in __init__
    self.categories=PupyCategories(self)
  File "/home/live/Documents/pupy/pupy/pupy/pupylib/PupyCategories.py", line 17, in __init__
    self.parse_categories()
  File "/home/live/Documents/pupy/pupy/pupy/pupylib/PupyCategories.py", line 21, in parse_categories
    for mod in self.pupsrv.iter_modules():
  File "/home/live/Documents/pupy/pupy/pupy/pupylib/PupyServer.py", line 424, in iter_modules
    yield self.get_module(module_name)
  File "/home/live/Documents/pupy/pupy/pupy/pupylib/PupyServer.py", line 453, in get_module
    module=loader.find_module(module_name).load_module(module_name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/live/Documents/pupy/pupy/pupy/modules/creddump.py", line 28, in <module>
    from modules.lib.windows.creddump.win32.domcachedump import dump_hashes
ImportError: No module named creddump.win32.domcachedump

**Comment by n1nj4sec** [comment]
````
git submodule init
git submodule update
```
