### ISSUE TITLE
pyshell error: WindowsError: [Error 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by belko-letyago** [n1nj4sec/pupy#21]
```
>> run pyshell
PupyPackageLoader: Error while loading package pyreadline.console.console2 (pyc) : [Error 193] %1 is not a valid Win32 application <code object <module> at 0000000004626C30, file "pyreadline\console\console2.pyc", line 9>
PupyPackageLoader: Error while loading package pyreadline.console (pyc) : [Error 193] %1 is not a valid Win32 application <code object <module> at 00000000030D7730, file "pyreadline\console\__init__.pyc", line 1>
PupyPackageLoader: Error while loading package pyreadline (pyc) : [Error 193] %1 is not a valid Win32 application <code object <module> at 0000000003098EB0, file "pyreadline\__init__.pyc", line 9>
PupyPackageLoader: Error while loading package readline (pyc) : [Error 193] %1 is not a valid Win32 application <code object <module> at 0000000003098A30, file "readline.pyc", line 5>
[-] (193, '%1 is not a valid Win32 application')

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "rpyc\core\protocol.pyc", line 305, in _dispatch_request
  File "rpyc\core\protocol.pyc", line 535, in _handle_call
  File "<string>", line 5, in _rinteract
  File "code.pyc", line 303, in interact
  File "<string>", line 110, in load_module
WindowsError: [Error 193] %1 is not a valid Win32 application
```

**Comment by n1nj4sec** [comment]
I can't reproduce the error, can you tell me on what version/arch of windows you get this error ?

**Comment by belko-letyago** [comment]
Win7 x64

**Comment by n1nj4sec** [comment]
ok, the bug was on x64 pupy processes. I forgot to clean up the libraryx64.zip after some dev tests, it works now :) thank's for your input
