### ISSUE TITLE
Error 13 : Permission Denied

### ISSUE THREAD

**Issue by udaybhasker007** [n1nj4sec/pupy#211]
Server started on x.x.x.x port 443 with transport ssl
>> ERROR:root:[Errno 13] Permission denied
Traceback (most recent call last):
  File "/home/myname/Downloads/pupy/pupy/pupylib/PupyServer.py", line 526, in run
    self.server = t.server(PupyService.PupyService, port = self.port, hostname=self.address, authenticator=authenticator, stream=t.stream, transport=t.server_transport, transport_kwargs=t.server_transport_kwargs, ipv6=self.ipv6)
  File "/home/myname/Downloads/pupy/pupy/network/lib/servers.py", line 225, in __init__
    ThreadPoolServer.__init__(self, *args, **kwargs)
  File "/home/myname/.local/lib/python2.7/site-packages/rpyc/utils/server.py", line 304, in __init__
    Server.__init__(self, *args, **kwargs)
  File "/home/myname/.local/lib/python2.7/site-packages/rpyc/utils/server.py", line 78, in __init__
    self.listener.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 13] Permission denied

Made a x86.exe file and executed on Windows
 ./pupysh.py script on ubuntu

but getting this. I'm not understanding is it really a code problem or pip libraries problem. Please help.
Thanks

**Comment by quentinhardy** [comment]
You have to be _root_ for opening a listening port between 1-1024 on Linux. Use the following keyword in Google for example: "_Privileged Ports Linux_".

You can run _pupysh.py_ with _sudo_ for example:
```
sudo ./pupysh.py
```

For information about _sudo_, see [https://help.ubuntu.com/community/RootSudo](https://help.ubuntu.com/community/RootSudo)

**Comment by udaybhasker007** [comment]
Server started on 10.80.24.87 port 443 with transport ssl
>> ERROR:root:[Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "/home/junggab/Downloads/pupy/pupy/pupylib/PupyServer.py", line 526, in run
    self.server = t.server(PupyService.PupyService, port = self.port, hostname=self.address, authenticator=authenticator, stream=t.stream, transport=t.server_transport, transport_kwargs=t.server_transport_kwargs, ipv6=self.ipv6)
  File "/home/junggab/Downloads/pupy/pupy/network/lib/servers.py", line 225, in __init__
    ThreadPoolServer.__init__(self, *args, **kwargs)
  File "/home/junggab/.local/lib/python2.7/site-packages/rpyc/utils/server.py", line 304, in __init__
    Server.__init__(self, *args, **kwargs)
  File "/home/junggab/.local/lib/python2.7/site-packages/rpyc/utils/server.py", line 78, in __init__
    self.listener.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address


If I run as sudo and this is the error and also forwarded port 443 using iptables. But dont understand the error.

**Comment by udaybhasker007** [comment]
I made my ip address 127.0.0.1 in pupy.conf so it started running but when I exit from the pupysh.py and re run it, its not showing the clients.

**Comment by n1nj4sec** [comment]
hello, 
Don't edit pupy.conf and let the default ipv6 address :: which is the equivalent of 0.0.0.0 in ipv6. The port will be reachable from both your ipv4 and ipv6 address. If you wish to drop the ipv6 support and bind on a ipv4 address anyway, set ipv6=false in the config
