### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by belko-letyago** [n1nj4sec/pupy#22]
Error when hostname contains non-ascii symbols

```
>> sessions
Traceback (most recent call last):
  File "./pupysh.py", line 62, in <module>
    pcmd.cmdloop()
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 259, in cmdloop
    cmd.Cmd.cmdloop(self, intro)
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 435, in do_sessions
    self.display(PupyCmd.table_format([x.desc for x in client_list], wl=["id", "user", "hostname", "platform", "release", "os_arch", "address"]))
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 194, in table_format
    diclist=obj2utf8(diclist)
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 113, in obj2utf8
    obj[i]=obj2utf8(obj[i])
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 110, in obj2utf8
    obj[k]=obj2utf8(obj[k])
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 120, in obj2utf8
    return obj.encode('utf8', errors='replace')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 5: ordinal not in range(128)

>> info
#>#>  PupyClient(id=2, user=user, hostname=user-▒▒, platform=Windows)  <#<#
macaddr   : EC:F7:89:2C:37:44
pid       : 8508
exec_path : C:\Users\user\pupy.exe
address   : 127.0.0.1
proc_arch : 64bit
hostname  : user-▒▒
os_arch   : AMD64
version   : 6.1.7601
release   : 7
```

**Comment by deathfantasy** [comment]
Open a python shell and run

```
import platform
platform.node()
```

What do you get?

**Comment by belko-letyago** [comment]
Issue is still reproducible:
```
>> sessions
Traceback (most recent call last):
  File "./pupysh.py", line 62, in <module>
    pcmd.cmdloop()
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 259, in cmdloop
    cmd.Cmd.cmdloop(self, intro)
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 435, in do_sessions
    self.display(PupyCmd.table_format([x.desc for x in client_list], wl=["id", "user", "hostname", "platform", "release", "os_arch", "address"]))
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 194, in table_format
    diclist=obj2utf8(diclist)
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 113, in obj2utf8
    obj[i]=obj2utf8(obj[i])
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 110, in obj2utf8
    obj[k]=obj2utf8(obj[k])
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 120, in obj2utf8
    return obj.encode('utf8', errors='replace')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 5: ordinal not in range(128)

>> info
macaddr   : FF:FF:FF:FF:FF:FF
pid       : 7392
exec_path : C:\Users\user\Downloads\pupy.exe
address   : 127.0.0.1
proc_arch : 64bit
hostname  : user-ПК
os_arch   : AMD64
version   : 6.1.7601
release   : 7
>> run pyshell
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import platform
>>> platform.node()
'user-\xcf\xca'
```

**Comment by deathfantasy** [comment]
Just for reference, what is your actual hostname?

**Comment by belko-letyago** [comment]
Hostname is "user-ПК". 
Encoding: 1251
System locale: Russian :)
```python
>>> print 'user-\xcf\xca'.decode('cp1251')
user-ПК
```

**Comment by belko-letyago** [comment]
Root cause found:
desc['hostname'] is already utf8 encoded while trying to obj.encode('utf8', errors='replace')
```
>> clients
Traceback (most recent call last):
  File "./pupysh.py", line 62, in <module>
    pcmd.cmdloop()
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 259, in cmdloop
    cmd.Cmd.cmdloop(self, intro)
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 406, in do_clients
    self.do_sessions(arg)
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 435, in do_sessions
    self.display(PupyCmd.table_format([x.desc for x in client_list], wl=["id", "user", "hostname", "platform", "release", "os_arch", "address"]))
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 194, in table_format
    diclist=obj2utf8(diclist)
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 113, in obj2utf8
    obj[i]=obj2utf8(obj[i])
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 110, in obj2utf8
    obj[k]=obj2utf8(obj[k])
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 120, in obj2utf8
    return obj.encode('utf8', errors='replace')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 5: ordinal not in range(128)

>> python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> pupsrv.clients[0].desc['hostname'] = pupsrv.clients[0].desc['hostname'].decode('utf8')
>>> 
>> clients
id  user  hostname   platform  release  os_arch  address        
----------------------------------------------------------------
1   user  user-ПК    Windows   7        AMD64    127.0.0.1

```
