### ISSUE TITLE
Ubuntu host and OSX client, keylogger dlsym(RTLD_DEFAULT, XOpenDisplay): symbol not found

### ISSUE THREAD

**Issue by ArThoX** [n1nj4sec/pupy#222]
Hi
The following error occurs starting the kl on osx client.

```
>> run gather/keylogger start
  File "<string>", line 86, in load_module
  File "<memimport>\keylogger.py", line 14, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
PupyPackageLoader: Error while loading package keylogger (py) : dlsym(RTLD_DEFAULT, XOpenDisplay): symbol not found
#>#>  PupyClient(id=1, user=serveurachat, hostname=mac.local, platform=Darwin)  <#<#
[-] dlsym(RTLD_DEFAULT, XOpenDisplay): symbol not found

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "<memimport>\rpyc\core\protocol.py", line 305, in _dispatch_request
  File "<memimport>\rpyc\core\protocol.py", line 547, in _handle_callattr
  File "<memimport>\rpyc\core\service.py", line 118, in __getitem__
  File "<string>", line 151, in exposed_getmodule
  File "<string>", line 118, in load_module
AttributeError: dlsym(RTLD_DEFAULT, XOpenDisplay): symbol not found

```

**Comment by n1nj4sec** [comment]
yep thx, I forgot the compatibility tag on this, the keylogger is only implemented for linux && windows

**Comment by ArThoX** [comment]
;'( k

**Comment by n1nj4sec** [comment]
@ArThoX you know if you have access to a mac, it would be dead easy to create a keylogger module for mac taking example on a script like https://github.com/justicesuh/python-keylogger/blob/master/keylogger.py and the module https://github.com/n1nj4sec/pupy/blob/master/pupy/packages/linux/all/keylogger.py or https://github.com/n1nj4sec/pupy/blob/master/pupy/packages/windows/all/pupwinutils/keylogger.py
