### ISSUE TITLE
error pupy address error

### ISSUE THREAD

**Issue by Axe-Usa** [n1nj4sec/pupy#258]
Hi i get one error with the address

**Comment by Axe-Usa** [comment]
i get this error when i use no-ip ip or ddns
ERROR:root:[Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "/home/omar/Github/pupy/pupy/pupylib/PupyServer.py", line 297, in run
    self.server = t.server(PupyService.PupyService, port = self.port, hostname=self.address, authenticator=authenticator, stream=t.stream, transport=t.server_transport, transport_kwargs=t.server_transport_kwargs, ipv6=self.ipv6)
  File "/home/omar/Github/pupy/pupy/network/lib/servers.py", line 119, in __init__
    ThreadedServer.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 78, in __init__
    self.listener.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address
