### ISSUE TITLE
Android APK issues on Kali Linux

### ISSUE THREAD

**Issue by vincentcox-ordina** [n1nj4sec/pupy#264]
I'm reading through the Wiki and closed issues but unfortunately I cannot solve the following error:
```
root@printer:~/pupy/client/android_sources# ./build.sh
^CTraceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.33.dev0', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.33.dev0-py2.7.egg/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.33.dev0-py2.7.egg/buildozer/__init__.py", line 1008, in run_command
    self.check_root()
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.33.dev0-py2.7.egg/buildozer/__init__.py", line 1052, in check_root
    cont = input_func('Are you sure you want to continue [y/n]? ')
KeyboardInterrupt
cat: ./.buildozer/android/platform/python-for-android/dist/pupy/templates/AndroidManifest.tmpl.xml: No such file or directory
Patching AndroidManifest template for BOOT_COMPLETED
sed: can't read ./.buildozer/android/platform/python-for-android/dist/pupy/templates/AndroidManifest.tmpl.xml: No such file or directory
Patching AndroidManifest template for excludeFromRecents
sed: can't read ./.buildozer/android/platform/python-for-android/dist/pupy/templates/AndroidManifest.tmpl.xml: No such file or directory
cp: cannot create regular file '.buildozer/android/platform/python-for-android/dist/pupy/src/': No such file or directory
cp: cannot create regular file '.buildozer/android/platform/python-for-android/dist/pupy/src/org/renpy/android/PythonService.java': No such file or directory
cp: cannot create regular file '.buildozer/android/platform/python-for-android/src/src/org/renpy/android/PythonActivity.java': No such file or directory
rm: cannot remove 'bin/*.apk': No such file or directory
# Check configuration tokens
Buildozer is running as root!
This is not recommended, and may lead to problems later.
```
Any idea's?

**Comment by n1nj4sec** [comment]
the problem is probably that you need to write "y"
try removing "2>&1 > /dev/null" line 7 of build.sh

**Comment by vincentcox-ordina** [comment]
Thank you very much, that dit the trick. However, I think I'm very close, but a new error appeared:
```
# Android packages installation done.
# Check application requirements
# Check garden requirements
# Compile platform
# Distribution compiled.
# Build the application #1
# Patched service/main.py to include applibs
# Package the application
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.33.dev0', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.33.dev0-py2.7.egg/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.33.dev0-py2.7.egg/buildozer/__init__.py", line 1029, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.33.dev0-py2.7.egg/buildozer/target.py", line 90, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.33.dev0-py2.7.egg/buildozer/target.py", line 107, in cmd_release
    self.buildozer.build()
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.33.dev0-py2.7.egg/buildozer/__init__.py", line 211, in build
    self.target.build_package()
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.33.dev0-py2.7.egg/buildozer/targets/android.py", line 765, in build_package
    copyfile(join(dist_dir, 'bin', apk), join(self.buildozer.bin_dir, apk))
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/root/pupy/client/android_sources/.buildozer/android/platform/python-for-android/dist/myapp/bin/MyApplication-0.1-release.apk'
copying the generated apk to ../../pupy/payload_templates/pupy.apk
cp: cannot stat 'bin/Pupy-0.1-release-unsigned.apk': No such file or directory

```

I really appreciate the time you take by answering these questions.

**Comment by vincentcox-ordina** [comment]
I fixed it by making editing the last line of build.sh to "cp bin/pupy-0.1-release.apk ../../pupy/payload_templates/pupy.apk". I also had to edit the buildozer.spec file to change the name to "pupy" instead of "My Application"
