### ISSUE TITLE
Compile pupygen in windows and run fine

### ISSUE THREAD

**Issue by Axe-Usa** [n1nj4sec/pupy#272]
Hi i tried compile pupygen and run with windows but i get this error:
```

> Traceback (most recent call last):
>   File "pupygen.py", line 13, in <module>
>     from network.conf import transports, launchers
>   File "C:\Users\moh\Desktop\pupy-master\pupy\network\conf.py", line 6, in <modu
> le>
>     from .lib.launchers.connect import ConnectLauncher
>   File "C:\Users\moh\Desktop\pupy-master\pupy\network\lib\__init__.py", line 4,
> in <module>
>     from .clients import PupyTCPClient, PupySSLClient, PupyProxifiedTCPClient, P
> upyProxifiedSSLClient, PupyAsyncClient, PupyUDPClient
>   File "C:\Users\moh\Desktop\pupy-master\pupy\network\lib\clients.py", line 5, i
> n <module>
>     from . import socks
>   File "C:\Users\moh\Desktop\pupy-master\pupy\network\lib\socks.py", line 72, in
>  <module>
>     raise ImportError('To run PySocks under windows you need to install win_inet
> _pton')
> ImportError: To run PySocks under windows you need to install win_inet_pton

```

**Comment by quentinhardy** [comment]
You have to install the python package named **_win_inet_pton_**.

You can install this package with the following command for example:
```
pip install win_inet_pton
```
