### ISSUE TITLE
Problem with get_info in android 

### ISSUE THREAD

**Issue by samdunsavy** [n1nj4sec/pupy#286]
>> run get_info
[-] JVM exception occurred: ConnectivityService: Neither user 10157 nor current process has android.permission.ACCESS_NETWORK_STATE.

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "<memimport>/rpyc/core/protocol.py", line 305, in _dispatch_request
  File "<memimport>/rpyc/core/protocol.py", line 535, in _handle_call
  File "<memimport>/pupydroid/utils.py", line 170, in isWiFiConnected
  File "jnius/jnius_export_class.pxi", line 906, in jnius.jnius.JavaMultipleMethod.__call__ (jnius/jnius.c:27875)
  File "jnius/jnius_export_class.pxi", line 638, in jnius.jnius.JavaMethod.__call__ (jnius/jnius.c:24269)
  File "jnius/jnius_export_class.pxi", line 715, in jnius.jnius.JavaMethod.call_method (jnius/jnius.c:25248)
  File "jnius/jnius_utils.pxi", line 93, in jnius.jnius.check_exception (jnius/jnius.c:3870)
JavaException: JVM exception occurred: ConnectivityService: Neither user 10157 nor current process has android.permission.ACCESS_NETWORK_STATE.

This is what I get.. I checked the manifest file and I guess there is no permission like "ACCESS_NETWORK_STATE"

**Comment by jboss38** [comment]
Working good for me. 
On 5.1.1 Android. 
What's ur Android version ?

**Comment by samdunsavy** [comment]
Mine is 6.0.1 I guess that's the problem...

**Comment by quentinhardy** [comment]
The apk generated **by default** by pupy **has not the ACCESS_NETWORK_STATE permission**. This is why you have this error: "user 10157 nor current process has android.permission.ACCESS_NETWORK_STATE".

This permission **has to be append to the manifest file** of the apk template.

You can use this method for modifying permissions of the apk for example: [https://www.reddit.com/r/Android/comments/11852r/how_to_modify_an_apk/](https://www.reddit.com/r/Android/comments/11852r/how_to_modify_an_apk/)

**Comment by n1nj4sec** [comment]
fixed in https://github.com/n1nj4sec/pupy/commit/f3fc9a5fca1b4e09a41c2bfe62bf03491d210447
