### ISSUE TITLE
What the helll is wrong >.< !!

### ISSUE THREAD

**Issue by its0x08** [n1nj4sec/pupy#296]
root@kali:~/Desktop/scripts/pupy/pupy# python pupygen.py -f apk connect --host 192.168.1.5:444
[+] generating payload ...
Traceback (most recent call last):
  File "pupygen.py", line 415, in <module>
    get_edit_apk(os.path.join(ROOT, "payload_templates","pupy.apk"), outpath, conf)
  File "pupygen.py", line 201, in get_edit_apk
    shutil.copy(path, new_path)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/root/Desktop/scripts/pupy/pupy/payload_templates/pupy.apk'
root@kali:~/Desktop/scripts/pupy/pupy# ls
conf  crypto  external  modules  network  packages  payload_templates  pp.py  pupy.conf  pupy.conf.default  pupygen.py  pupygen.pyc  pupylib  pupysh.py  pupysh.pyc  scriptlets
root@kali:~/Desktop/scripts/pupy/pupy# python pupygen.py -f ps1_oneliner connect --host 192.168.1.5:444 --transport http
Traceback (most recent call last):
  File "pupygen.py", line 468, in <module>
    serve_ps1_payload(conf, link_ip=link_ip, port=args.ps1_oneliner_listen_port, useTargetProxy=True)
  File "/root/Desktop/scripts/pupy/pupy/pupylib/payloads/ps1_oneliner.py", line 143, in serve_ps1_payload
    server = ps1_HTTPServer((ip, port), conf, link_ip, port, ssl, useTargetProxy)
  File "/root/Desktop/scripts/pupy/pupy/pupylib/payloads/ps1_oneliner.py", line 132, in __init__
    HTTPServer.__init__(self, server_address, PupyPayloadHTTPHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
root@kali:~/Desktop/scripts/pupy/pupy# python pupygen.py -f ps1_oneliner connect --host 192.168.1.5:44 --transport http
Traceback (most recent call last):
  File "pupygen.py", line 468, in <module>
    serve_ps1_payload(conf, link_ip=link_ip, port=args.ps1_oneliner_listen_port, useTargetProxy=True)
  File "/root/Desktop/scripts/pupy/pupy/pupylib/payloads/ps1_oneliner.py", line 143, in serve_ps1_payload
    server = ps1_HTTPServer((ip, port), conf, link_ip, port, ssl, useTargetProxy)
  File "/root/Desktop/scripts/pupy/pupy/pupylib/payloads/ps1_oneliner.py", line 132, in __init__
    HTTPServer.__init__(self, server_address, PupyPayloadHTTPHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
root@kali:~/Desktop/scripts/pupy/pupy# python pupygen.py -f ps1_oneliner connect --host 192.168.1.5:344 --transport http
Traceback (most recent call last):
  File "pupygen.py", line 468, in <module>
    serve_ps1_payload(conf, link_ip=link_ip, port=args.ps1_oneliner_listen_port, useTargetProxy=True)
  File "/root/Desktop/scripts/pupy/pupy/pupylib/payloads/ps1_oneliner.py", line 143, in serve_ps1_payload
    server = ps1_HTTPServer((ip, port), conf, link_ip, port, ssl, useTargetProxy)
  File "/root/Desktop/scripts/pupy/pupy/pupylib/payloads/ps1_oneliner.py", line 132, in __init__
    HTTPServer.__init__(self, server_address, PupyPayloadHTTPHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
root@kali:~/Desktop/scripts/pupy/pupy# pkill python
root@kali:~/Desktop/scripts/pupy/pupy# python pupygen.py -f ps1_oneliner connect --host 192.168.1.5:344 --transport http
Traceback (most recent call last):
  File "pupygen.py", line 468, in <module>
    serve_ps1_payload(conf, link_ip=link_ip, port=args.ps1_oneliner_listen_port, useTargetProxy=True)
  File "/root/Desktop/scripts/pupy/pupy/pupylib/payloads/ps1_oneliner.py", line 143, in serve_ps1_payload
    server = ps1_HTTPServer((ip, port), conf, link_ip, port, ssl, useTargetProxy)
  File "/root/Desktop/scripts/pupy/pupy/pupylib/payloads/ps1_oneliner.py", line 132, in __init__
    HTTPServer.__init__(self, server_address, PupyPayloadHTTPHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
root@kali:~/Desktop/scripts/pupy/pupy#

**Comment by n1nj4sec** [comment]
problem between the keyboard and the chair

**Comment by ChipWolf** [comment]
ID 10 T Error.
