### ISSUE TITLE
PS command fails

### ISSUE THREAD

**Issue by byt3bl33d3r** [n1nj4sec/pupy#3]
The following error occurs when executing the ps command on a windows client: seems like some files are missing from the psutils library in the repo 
```python
>> ps
[-] cannot import name _common

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "rpyc\core\protocol.pyc", line 305, in _dispatch_request
  File "rpyc\core\protocol.pyc", line 547, in _handle_callattr
  File "rpyc\core\service.pyc", line 118, in __getitem__
  File "<string>", line 58, in exposed_getmodule
  File "<string>", line 97, in load_module
ImportError: cannot import name _common
```

**Comment by artagel** [comment]
Same here.

**Comment by n1nj4sec** [comment]
should be fixed, this damn .gitignore file removed all the .pyd from packages x)

**Comment by n1nj4sec** [comment]
thanks :+1:
