### ISSUE TITLE
ImportError: No module named netifaces

### ISSUE THREAD

**Issue by xSynthx** [n1nj4sec/pupy#304]
When I try to run `python pupygen.py` I get the following error:

Traceback (most recent call last):
  File "pupygen.py", line 7, in <module>
    from pupylib.utils.network import get_local_ip
  File "/home/Synthx/pupy/pupy/pupylib/utils/network.py", line 2, in <module>
    import netifaces
ImportError: No module named netifaces

I have looked it up, but it isnt working.

**Comment by xSynthx** [comment]
I have fixed my error, I guess I never added the python-dev via
`sudo apt-get install python-dev`
once I ran ^^^ I ran
`sudo pip install netifaces`
Thus fixing my run error, I hope this will also help someone else out! :)

**Comment by xSynthx** [comment]
I have fixed my error, I guess I never added the python-dev via
`sudo apt-get install python-dev`
once I ran ^^^ I ran
`sudo pip install netifaces`
Thus fixing my run error, I hope this will also help someone else out! :)
