### ISSUE TITLE
pupy.sh error

### ISSUE THREAD

**Issue by Duartebm** [n1nj4sec/pupy#31]
Every time I try opening pupy.sh this happens:

root@Anonymous:~/Desktop/pupy-master/pupy# python pupysh.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/root/Desktop/pupy-master/pupy/pupylib/PupyServer.py", line 251, in run
    self.server = ThreadPoolServer(PupyService.PupyService, port = self.port, hostname=self.address, authenticator=self.authenticator)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 304, in __init__
    Server.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 78, in __init__
    self.listener.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address

**Comment by n1nj4sec** [comment]
It looks like you have a problem between your computer and your chair ! did you change the default port ? do you have the right to bind on that port ? do you already have something bind on that port ?

**Comment by marte3707** [comment]
I' ve the same problem. tried to change the port in pupy.conf from 443 to 4444 but aslo have the problem

**Comment by n1nj4sec** [comment]
strange, what distrib are you running the server on ? did you tried to start pupy as root ? do you see a program listening on that address when you type "netstat -anpt | grep LISTEN" ? if yes which program is it ?

**Comment by cacaocaca** [comment]
I use port 443 The same problem my machine is kali linux 2.0 yes i start puppy as root and i no see program listen when i start root@kali:~# netstat -anpt | grep LISTEN
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      791/postgres    
tcp        0      0 127.0.0.1:9391          0.0.0.0:*               LISTEN      765/openvassd: Wait
tcp        0      0 127.0.0.1:9392          0.0.0.0:*               LISTEN      658/gsad        
tcp        0      0 127.0.0.1:5939          0.0.0.0:*               LISTEN      797/teamviewerd 
tcp6       0      0 ::1:5432                :::*                    LISTEN      791/postgres    
tcp6       0      0 :::80                   :::*                    LISTEN      5583/apache2    

Please resolve this issue thanks ..

**Comment by cacaocaca** [comment]
Ok i see now the problem is when i use my pubblich ip while if i use my local ip and edit pupy.conf work but i would like he work with ip pubblic .. Congratulation for your work .

**Comment by TechnoTroll** [comment]
Sry for reopening this topic but i have the same problem 

my pupy.conf listen on port 443 and my exe too
`#listen on all interfaces by default
address = 192.168.10.220
port = 443
ipv6 = true
keyfile = crypto/server.pem
certfile = crypto/cert.pem
...`

If i want to start pupysh.py, i've got this output

`[*] Server started on 192.168.10.220 port 443 with transport ssl
>> ERROR:root:[Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "/home/flo/Dokumente/pupy/pupy/pupylib/PupyServer.py", line 526, in run
    self.server = t.server(PupyService.PupyService, port = self.port, hostname=self.address, authenticator=authenticator, stream=t.stream, transport=t.server_transport, transport_kwargs=t.server_transport_kwargs, ipv6=self.ipv6)
  File "/home/flo/Dokumente/pupy/pupy/network/lib/servers.py", line 225, in __init__
    ThreadPoolServer.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 304, in __init__
    Server.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 78, in __init__
    self.listener.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address
`

Without root it looks like this
`[*] Server started on 192.168.10.220 port 443 with transport ssl
>> ERROR:root:[Errno 13] Permission denied
Traceback (most recent call last):
  File "/home/flo/Dokumente/pupy/pupy/pupylib/PupyServer.py", line 526, in run
    self.server = t.server(PupyService.PupyService, port = self.port, hostname=self.address, authenticator=authenticator, stream=t.stream, transport=t.server_transport, transport_kwargs=t.server_transport_kwargs, ipv6=self.ipv6)
  File "/home/flo/Dokumente/pupy/pupy/network/lib/servers.py", line 225, in __init__
    ThreadPoolServer.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 304, in __init__
    Server.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 78, in __init__
    self.listener.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 13] Permission denied
`

Would be glad, if you can help me

**Comment by holyknightrolex** [comment]
I also have the same problem on cannot assign requested address and i dont know to fox it.. Im glad someone can help with this issue

**Comment by EnhboldH** [comment]
When victim click my payload I got this error 
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/Desktop/tools/pupy/pupy/network/lib/servers.py", line 119, in _setup_connection
    config=config
  File "/root/Desktop/tools/pupy/pupy/network/lib/connection.py", line 35, in __init__
    Connection.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument '_lazy'

Exception AttributeError: "'PupyConnection' object has no attribute '_closed'" in <object repr() failed> ignored
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/Desktop/tools/pupy/pupy/network/lib/servers.py", line 119, in _setup_connection
    config=config
  File "/root/Desktop/tools/pupy/pupy/network/lib/connection.py", line 35, in __init__
    Connection.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument '_lazy'
