### ISSUE TITLE
'utf8' codec can't decode byte

### ISSUE THREAD

**Issue by huakairuoxiangxi** [n1nj4sec/pupy#321]
use  ps command
have chinese word.

[-] 'utf8' codec can't decode byte 0xc5 in position 11: invalid continuation byte

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\rpyc\core\protocol.py", line 305, in _dispatch_request
  File "C:\Python27\lib\site-packages\rpyc\core\protocol.py", line 535, in _handle_call
  File "<string>", line 129, in exposed_json_dumps
  File "C:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc5 in position 11: invalid continuation byte

**Comment by quentinhardy** [comment]
I have tested with some Chinese words in a program name and the _ps_ command shows _?????_ instead of special chars.
I don't know where the error comes from -:(

**Comment by quentinhardy** [comment]
I have tested pupy on a wind2012 server with Chinese language (simplified) enabled and I have not your error.

**Comment by alxchk** [comment]
This may be resolved with this commit - https://github.com/alxchk/pupy/commit/f6b1b03b296cdb2823ca4c4ffa002d6ffdbe31a1

But I'm not 100% sure

**Comment by LAzyFrAAnk** [comment]
Have tested and work fine on win XP, 7 and 10 with Chinese (simplified and traditional)
