### ISSUE TITLE
install requirements.txt issue

### ISSUE THREAD

**Issue by rtriplettOnGit** [n1nj4sec/pupy#336]
Hello Everyone,

I'm new to linux and I'm trying to install the requirements.txt file using the pip install -r requirements.txt command ,but I keep getting an error. Can someone please help me out with this. I'm using Kali linux 2.0 and my level is still beginner. I would like to learn more about this though. Thanks in advance for your help.

Error=
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 274, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1632, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 109, in __init__
    self.prereleases = any([is_prerelease(x[1]) and x[0] != "!=" for x in self.req.specs])
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 739, in is_prerelease
    return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
TypeError: 'int' object is not iterable

Storing debug log for failure in /root/.pip/pip.log

**Comment by rtriplettOnGit** [comment]
To me it looks like I'm missing some packages from python maybe?

**Comment by n1nj4sec** [comment]
try upgrading pip and/or reinstalling pip, it seems broken

**Comment by rtriplettOnGit** [comment]
Thank you so much! That point me in the right area to find my error. I had to re-install pip and install python3 then it worked. Thanks!
