### ISSUE TITLE
EOFErrors after running exe_x86 and exe_x64 binaries

### ISSUE THREAD

**Issue by ABorrello** [n1nj4sec/pupy#345]
Earlier today I generated two payloads (exe_x86 and exe_x64) and installed them onto my testing machines to see if they are viable to use for my day to day pentesting.

Unfortunately, as soon as I start up pupysh I am spammed with the following error messages:
`
ERROR:root:Traceback (most recent call last):
  File "/root/Documents/pupy/pupy/pupylib/PupyService.py", line 58, in on_connect
    self.execute=self._conn.root.execute
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 148, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/root/Documents/pupy/pupy/network/lib/servers.py", line 54, in sync_request
    raise EOFError()
EOFError
`
and
`
ERROR:root:Traceback (most recent call last):
  File "/root/Documents/pupy/pupy/pupylib/PupyService.py", line 58, in on_connect
    self.execute=self._conn.root.execute
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 148, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/root/Documents/pupy/pupy/network/lib/servers.py", line 38, in sync_request
    if not self.serve(10):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 387, in serve
    data = self._recv(timeout, wait_for_lock = True)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 344, in _recv
    if self._channel.poll(timeout):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/channel.py", line 43, in poll
    return self.stream.poll(timeout)
  File "/root/Documents/pupy/pupy/network/lib/streams/PupySocketStream.py", line 76, in poll
    result = ( len(self.upstream)>0 or self.sock_poll(timeout) )
  File "/root/Documents/pupy/pupy/network/lib/streams/PupySocketStream.py", line 86, in sock_poll
    self._read()
  File "/root/Documents/pupy/pupy/network/lib/streams/PupySocketStream.py", line 67, in _read
    raise EOFError(ex)
EOFError: [Errno 104] Connection reset by peer
`
and
`
ERROR:root:Traceback (most recent call last):
  File "/root/Documents/pupy/pupy/pupylib/PupyService.py", line 58, in on_connect
    self.execute=self._conn.root.execute
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 148, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/root/Documents/pupy/pupy/network/lib/servers.py", line 38, in sync_request
    if not self.serve(10):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 387, in serve
    data = self._recv(timeout, wait_for_lock = True)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 344, in _recv
    if self._channel.poll(timeout):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/channel.py", line 43, in poll
    return self.stream.poll(timeout)
  File "/root/Documents/pupy/pupy/network/lib/streams/PupySocketStream.py", line 76, in poll
    result = ( len(self.upstream)>0 or self.sock_poll(timeout) )
  File "/root/Documents/pupy/pupy/network/lib/streams/PupySocketStream.py", line 86, in sock_poll
    self._read()
  File "/root/Documents/pupy/pupy/network/lib/streams/PupySocketStream.py", line 70, in _read
    raise EOFError("connection closed by peer")
EOFError: connection closed by peer
`
and
`Exception in thread Thread-154:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/Documents/pupy/pupy/network/lib/servers.py", line 131, in _setup_connection
    wrapper, credentials = self.authenticator(sock)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/authenticators.py", line 79, in __call__
    sock2 = ssl.wrap_socket(sock, **kwargs)
  File "/usr/lib/python2.7/ssl.py", line 943, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error
`
These error messages only started appearing after I installed the payloads on two Windows 10 systems (one 64 bit and one 32 bit.) It is also important to note that I can not open a session to either of them.

I currently use pupy for OSX pentesting and that works fine, so I would really like to try to get these binary executables working for Windows.

Let me know if anyone has any ideas?

**Comment by n1nj4sec** [comment]
could you try with the last version ? there has been a lot of changes
