### ISSUE TITLE
ERROR:root:Corrupted file: /root/pupy/pupy/pupylib/../crypto/credentials.py

### ISSUE THREAD

**Issue by drivebyde** [n1nj4sec/pupy#372]
Hey all,
i have a Problem with the Builder. The First Build Works fine.
But after that i get an error:
My Os Debian 8 64 Bit

```
[+] Generate client: windows/x86
[C] launcher: connect
[C] launcher_args: ['--host', 'MYIP&PORT', '-t', 'ssl']
[C] debug: False
[C] offline_script:
[I] Credentials password:
ERROR:root:bad decrypt pad (245)
Traceback (most recent call last):
  File "./pupygen.py", line 581, in <module>
    pupygen(parser.parse_args(), config)
  File "./pupygen.py", line 468, in pupygen
    arch=args.arch, shared=args.shared, debug=args.debug
  File "./pupygen.py", line 294, in generate_binary_from_template
    return generator(template, config), filename, makex
  File "./pupygen.py", line 63, in get_edit_binary
    new_conf = marshal.dumps(compile(get_raw_conf(conf), '<string>', 'exec'))
  File "./pupygen.py", line 84, in get_raw_conf
    credentials = Credentials(role='client')
  File "/ratte/pupy/pupy/pupylib/PupyCredentials.py", line 206, in __init__
    encryptor.decrypt(StringIO(content), fcontent)
  File "/ratte/pupy/pupy/pupylib/PupyCredentials.py", line 162, in decrypt
    raise ValueError("bad decrypt pad (%d)" % padding_length)
ValueError: bad decrypt pad (245)
bad decrypt pad (245)
root@localhost:/ratte/pupy/pupy# ERROR:root:bad decrypt pad (245)
```

**Comment by n1nj4sec** [comment]
Your password is incorrect, enter the same password as the first time you generated the file

**Comment by b0nete** [comment]
I have same problem. The curious is a never enter a password.

**Comment by Fabbe041** [comment]
how can i change it?
