### ISSUE TITLE
Clients do not connect (Error 0)

### ISSUE THREAD

**Issue by ABorrello** [n1nj4sec/pupy#385]
Not sure if this has already been posted (I did some searching but could not find anything...)
This error occurs every time one of my clients try to connect (currently running a windows 64bit exe payload & a macOS pure python payload.)

```
Exception in thread Thread-763:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/Documents/pupy/pupy/network/lib/servers.py", line 79, in _setup_connection
    wrapper, credentials = self.authenticator(sock)
  File "/root/Documents/pupy/pupy/network/transports/ssl/conf.py", line 56, in __call__
    ciphers=self.ciphers
  File "/usr/lib/python2.7/ssl.py", line 943, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error
```

Let me know if you need any more information...

**Comment by n1nj4sec** [comment]
Could you try again to see if the problem still persist ? if it does try the rsa transport to see if it's only ssl related

**Comment by ABorrello** [comment]
Hi, seems to be a problem with the old payloads.
Appears to be fixed now, thanks!

**Comment by DevarshDani** [comment]
I still receive this same error can anyone tell me the fix for this issue? I am using python2.7

**Comment by pwna5aurus** [comment]
I get this error when an errant portscanner or some other out-of-spec client connects to the socket.  The try/exception doesn't seem to handle it...looking at a fix.
