### ISSUE TITLE
Can't generate payload with pupygen.py

### ISSUE THREAD

**Issue by mattfrias** [n1nj4sec/pupy#396]
Launched with Python2 I get this error

python ./pupygen.py -f py connect --transport ssl --host 192.168.0.125

Traceback (most recent call last):
  File "./pupygen.py", line 7, in <module>
    from pupylib.utils.network import get_listener_ip, get_listener_port
  File "/home/mattfrias/pupy/pupy/pupylib/__init__.py", line 6, in <module>
    from PupyServer import *
  File "/home/mattfrias/pupy/pupy/pupylib/PupyServer.py", line 30, in <module>
    from pupylib.PupyDnsCnc import PupyDnsCnc
  File "/home/mattfrias/pupy/pupy/pupylib/PupyDnsCnc.py", line 11, in <module>
    import requests
ImportError: No module named requests

With Python3 I get this error

python3 ./pupygen.py -f py connect --transport ssl --host 192.168.0.125

File "./pupygen.py", line 117
    print colorize("[+] ", "green") + 'Required credentials:\n{}'.format(
                 ^
SyntaxError: invalid syntax

**Comment by n1nj4sec** [comment]
```pip install requests```
