### ISSUE TITLE
can't run pupysh.py

### ISSUE THREAD

**Issue by Blackmax7065** [n1nj4sec/pupy#418]
./pupysh.py

everytime i run this it gives me this:

Traceback (most recent call last):
  File "./pupysh.py", line 33, in <module>
    import network.conf
  File "/home/Blackmax2907/pupy/pupy/network/conf.py", line 6, in <module>
    from .lib.launchers.connect import ConnectLauncher
  File "/home/Blackmax2907/pupy/pupy/network/lib/__init__.py", line 2, in <module>
    from .streams import *
  File "/home/Blackmax2907/pupy/pupy/network/lib/streams/__init__.py", line 3, in <module>
    from PupySocketStream import *
  File "/home/Blackmax2907/pupy/pupy/network/lib/streams/PupySocketStream.py", line 9, in <module>
    from rpyc.core import SocketStream, Connection, Channel
ImportError: No module named rpyc.core

**Comment by glides** [comment]
ImportError: No module named rpyc.core

You're missing some dependencies.

**Comment by ndragon798** [comment]
Try running `sudo -H pip install -r requirements.txt`  make sure you are in the folder with the requirements file.

**Comment by quentinhardy** [comment]
I think this issue can be closed now.
