### ISSUE TITLE
Android Service Termination Issue & Proposed Solution

### ISSUE THREAD

**Issue by nostaldamask** [n1nj4sec/pupy#427]
Issue: The reference to syscall on line 62 of `pupyimporter.py` causes an error on android that terminates the android service:

```
I/python  ( 9468): Traceback (most recent call last):
I/python  ( 9468):   File "/root/pupy/client/android_sources/.buildozer/android/app/service/main.py", line 11, in <module>
I/python  ( 9468):   File "/tmp/tmp_pupy_kpo4In/pp.py", line 1, in <module>
I/python  ( 9468):   File "<string>", line 6, in <module>
I/python  ( 9468):   File "<string>", line 62, in <module>
I/python  ( 9468):   File "/root/pupy/client/android_sources/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/ctypes/__init__.py", line 369, in __getattr__
I/python  ( 9468):   File "/root/pupy/client/android_sources/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/ctypes/__init__.py", line 374, in __getitem__
I/python  ( 9468): AttributeError: Symbol not found: load_library[1093]: Library '/data/data/org.pupy.pupy/files/lib/python2.7/lib-dynload/_imaging.so' not found
I/python  ( 9468): Python for android ended.
```

Proposed Solution: The issue can be resolved by modifying the `if` statement on line 60 of `pupyimporter.py` to exclude android platforms:

```
--- a/pupy/packages/all/pupyimporter.py
+++ b/pupy/packages/all/pupyimporter.py
@@ -57,7 +57,14 @@ except ImportError:
     allow_system_packages = True
     import ctypes
     import platform
-    if sys.platform!="win32":
+    is_android = False
+    try:
+        from kivy.utils import platform as kivy_plat
+        if kivy_plat=="android":
+            is_android=True
+    except:
+        pass
+    if (sys.platform!="win32") and (not is_android):
```
The android check code is taken from `pp.py`, I haven't been able to confirm whether the change will cause any side effects on non-android platforms.

**Comment by alxchk** [comment]
Try android payload from my unstable tree - https://github.com/alxchk/pupy.
It was moved to the new buildozer/p4a toolchain
