### ISSUE TITLE
Issue with screenshot on linux

### ISSUE THREAD

**Issue by AkelMaister** [n1nj4sec/pupy#436]
Hello!

When i try to make screenshote with module screenshote on client (PC with linux) i get error:
```
>> run -f 1 screenshot
[-] 'MSS' object has no attribute 'enum_display_monitors'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "./site-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
  File "./site-packages/rpyc/core/protocol.py", line 535, in _handle_call
  File "screenshot.py", line 48, in screenshot
AttributeError: 'MSS' object has no attribute 'enum_display_monitors'
```
MSS module version:
```
# pip freeze | grep mss
mss==2.0.0
```
I try to install latest version of mss module, but from mss v3 realy lost attribute enum_display_monitors.

Python version:
```
# python -V
Python 2.7.5
```

But with windows client all is good. 
Have you same ideas about this issue?

**Comment by AkelMaister** [comment]
Hm... i fix my issue.
For this i reboot client PC and after reboot i get another error: 
```
run -f 1 screenshot
WARNING:root:Path contains unsafe binary objects: libmss.so
[-] Couldn't find package: mss
```
After that, i upgrade mss to version 2.0.22 (latest v2 version), then try again and... FIX!
