### ISSUE TITLE
Install completely BUT ./pupygen.py errored

### ISSUE THREAD

**Issue by linuxprj** [n1nj4sec/pupy#469]
Hi everyone,
I installed it completely without error but when I'm running "./pupygen.py -h" command, I got an error.
```
============
ERROR:
root@sb9044bf3:/opt/pupy/pupy# ./pupygen.py
Traceback (most recent call last):
  File "./pupygen.py", line 7, in <module>
    from pupylib.utils.network import get_listener_ip, get_listener_port
  File "/opt/pupy/pupy/pupylib/__init__.py", line 6, in <module>
    from PupyServer import *
  File "/opt/pupy/pupy/pupylib/PupyServer.py", line 30, in <module>
    from pupylib.PupyDnsCnc import PupyDnsCnc
  File "/opt/pupy/pupy/pupylib/PupyDnsCnc.py", line 11, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
root@sb9044bf3:/opt/pupy/pupy#
==============================================================
```
```
Note:
The flowing installation packages.
pip,pip2,pip3
python2.7,python3,python3.5
pip install future
apt-get install python-requests-futures
apt-get install python3-requests-futures
*******************************************
I read all issues for resolving problem, but no resolve for this.***
Please help me to resolve it..                 **
Thanks************************************

**Comment by generatorada** [comment]
rm -rf /usr/lib/python2.7/dist-packages/OpenSSL
rm -rf /usr/lib/python2.7/dist-packages/pyOpenSSL-0.15.1.egg-info
pip install pyopenssl
