### ISSUE TITLE
a problem with the screeshot module..

### ISSUE THREAD

**Issue by th4ne** [n1nj4sec/pupy#496]
`run screenshot 
[-] 'module' object has no attribute 'takeScreenshot'

========= Remote Traceback (1) =========
Traceback (most recent call last):
AttributeError: 'module' object has no attribute 'takeScreenshot'
Traceback (most recent call last):
  File "/root/Documentos/pupy/pupy/pupylib/PupyJob.py", line 129, in module_worker
    module.run(args)
  File "/root/Documentos/pupy/pupy/modules/screenshot.py", line 75, in run
    rscreenshot.takeScreenshot()
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 153, in __getattr__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 72, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/root/Documentos/pupy/pupy/network/lib/connection.py", line 109, in sync_request
    raise obj
AttributeError: 'module' object has no attribute 'takeScreenshot'

========= Remote Traceback (1) =========
Traceback (most recent call last):
AttributeError: 'module' object has no attribute 'takeScreenshot'
`

**Comment by HorneyAttorney** [comment]
I have the same issue

**Comment by th4ne** [comment]
the master version does not have this bug...

I use the master version only for that
