### ISSUE TITLE
ValueError: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by sp1k31973** [n1nj4sec/pupy#505]
Only 100 Connection whats is the maximum ?

exitException in thread Thread-2895:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/pupy/pupy/network/lib/servers.py", line 156, in _authenticate_and_serve_client
    connection.serve(interval or 10)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 442, in serve
    return self.sync_recv_and_dispatch(timeout, wait_for_lock=True)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 414, in sync_recv_and_dispatch
    data = self._recv(timeout, wait_for_lock = False)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 387, in _recv
    if self._channel.poll(timeout):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/channel.py", line 43, in poll
    return self.stream.poll(timeout)
  File "/root/pupy/pupy/network/lib/streams/PupySocketStream.py", line 120, in poll
    result = ( len(self.upstream)>0 or self.sock_poll(timeout) )
  File "/root/pupy/pupy/network/lib/streams/PupySocketStream.py", line 130, in sock_poll
    to_read, _, to_close = select([self.sock], [], [self.sock], timeout)
ValueError: filedescriptor out of range in select()

**Comment by n1nj4sec** [comment]
try to increase ulimit
