### ISSUE TITLE
./pupygen.py

### ISSUE THREAD

**Issue by Soman-Kumar** [n1nj4sec/pupy#507]
Whenever type this code I get this error.

Traceback (most recent call last):
  File "./pupygen.py", line 7, in <module>
    from pupylib.utils.network import get_listener_ip, get_listener_port
  File "/root/pupy/pupy/pupylib/__init__.py", line 6, in <module>
    from PupyServer import *
  File "/root/pupy/pupy/pupylib/PupyServer.py", line 30, in <module>
    from pupylib.PupyDnsCnc import PupyDnsCnc
  File "/root/pupy/pupy/pupylib/PupyDnsCnc.py", line 4, in <module>
    from network.lib.picocmd.server import *
  File "/root/pupy/pupy/network/lib/picocmd/server.py", line 17, in <module>
    import socketserver
ImportError: No module named socketserver

As I am new to linux I don't know very much about it. Is there something Wrong with the installation.

**Comment by kres0345** [comment]
still same issue
