### ISSUE TITLE
Screenshot module does not work.

### ISSUE THREAD

**Issue by kernel-pan-ic** [n1nj4sec/pupy#510]
I am on Ubuntu 17.04, my I guess "target" is on Windows 10 and whenever I do run gather/screenshot, it just gives me this error:
`[-] 'MSS' object has no attribute 'enum_display_monitors'

========= Remote Traceback (1) =========
Traceback (most recent call last):
AttributeError: 'MSS' object has no attribute 'enum_display_monitors'
Traceback (most recent call last):
  File "/home/liam/Desktop/pupy/pupy/pupylib/PupyJob.py", line 129, in module_worker
    module.run(args)
  File "/home/liam/Desktop/pupy/pupy/modules/screenshot.py", line 75, in run
    screenshots, error = rscreenshot.screenshot(args.screen)
  File "/home/liam/.local/lib/python2.7/site-packages/rpyc/core/netref.py", line 199, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/home/liam/.local/lib/python2.7/site-packages/rpyc/core/netref.py", line 72, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/home/liam/Desktop/pupy/pupy/network/lib/connection.py", line 109, in sync_request
    raise obj
AttributeError: 'MSS' object has no attribute 'enum_display_monitors'

========= Remote Traceback (1) =========
Traceback (most recent call last):
AttributeError: 'MSS' object has no attribute 'enum_display_monitors'`
I am happy to give any logfiles. I don't have any idea what has gone wrong, I'm not very familiar with Python.

**Comment by kernel-pan-ic** [comment]
I found the solution, I just had to install mss 2.0.22, because I had a later version installed. I just did:
`pip uninstall mss
pip install mss==2.0.22`

**Comment by SC4RECOIN** [comment]
3.0.0 (2017-07-06)
```
Removed enum_display_monitors() method. Use monitors property instead.
```

**Comment by NelsonLee-NTU** [comment]
> I found the solution, I just had to install mss 2.0.22, because I had a later version installed. I just did:
> `pip uninstall mss pip install mss==2.0.22`

This works for me! I had mss-5.0.0 before and it didn't work
