### ISSUE TITLE
Circular dependency issue with PupyCredentials and PupyCmd

### ISSUE THREAD

**Issue by GreyDireWolf** [n1nj4sec/pupy#535]
I'm having trouble while running pupysh.py
``` wolf pupy  python2 pupysh.py 
Traceback (most recent call last):
  File "pupysh.py", line 36, in <module>
    from pupylib import *
  File "/home/wolf/Apps/pupy/pupy/pupylib/__init__.py", line 6, in <module>
    from PupyCmd import *
  File "/home/wolf/Apps/pupy/pupy/pupylib/PupyCmd.py", line 50, in <module>
    import pupygen
  File "/home/wolf/Apps/pupy/pupy/pupygen.py", line 19, in <module>
    from pupylib import PupyCredentials
ImportError: cannot import name PupyCredentials
```
I think this is circular dependency issue

**Comment by AlessandroZ** [comment]
Hi, 

I had exactly the same issue on a fresh install of Ubuntu 17.10. 
```
./pupysh.py --port 1234
Traceback (most recent call last):
  File "./pupysh.py", line 36, in <module>
    from pupylib import PupyServer
  File "/home/yo/Documents/Tools/pupy/pupy/pupylib/__init__.py", line 6, in <module>
    from PupyCmd import *
  File "/home/yo/Documents/Tools/pupy/pupy/pupylib/PupyCmd.py", line 50, in <module>
    import pupygen
  File "/home/yo/Documents/Tools/pupy/pupy/pupygen.py", line 19, in <module>
    from pupylib import PupyCredentials
ImportError: cannot import name PupyCredentials
```

To fix it, try to run `./pupygen.py -h`. It should failed giving you a more explicit error, here is mine: 
```
Traceback (most recent call last):
  File "./pupygen.py", line 7, in <module>
    from pupylib.utils.network import get_listener_ip, get_listener_port
  File "/home/yo/Documents/pupy/pupy/pupylib/__init__.py", line 6, in <module>
    from PupyCmd import *
  File "/home/yo/Documents/pupy/pupy/pupylib/PupyCmd.py", line 50, in <module>
    import pupygen
  File "/home/yo/Documents/pupy/pupy/pupygen.py", line 27, in <module>
    import pylzma
ImportError: No module named pylzma
```
All these dependencies are on the `requirements.txt` file. However, some dependencies failed doing `pip install -r requirements.txt`. So I had to install some of them manually. 

Try to fix all your errors, installing what's missing, it should work. 

Here are some dependencies I had to install on a fresh ubuntu install: 
```
sudo apt install python-dev
sudo apt install python-m2crypto
sudo apt install python-xlib
```
And for pyautogui: 
```
git clone https://github.com/asweigart/pyautogui
cd pyautogui
sudo python setup.py install
```

Hope it will work.

**Comment by GreyDireWolf** [comment]
Ok i reinstalled fresh pupy on my arch machine and installed pyautogui from repo but now i'm getting this error
```
Traceback (most recent call last):
  File "pupysh.py", line 36, in <module>
    from pupylib import PupyServer
  File "/home/wolf/Apps/pupy/pupy/pupylib/__init__.py", line 7, in <module>
    from PupyServer import *
  File "/home/wolf/Apps/pupy/pupy/pupylib/PupyServer.py", line 30, in <module>
    from pupylib.PupyDnsCnc import PupyDnsCnc
  File "/home/wolf/Apps/pupy/pupy/pupylib/PupyDnsCnc.py", line 4, in <module>
    from network.lib.picocmd.server import *
  File "/home/wolf/Apps/pupy/pupy/network/lib/picocmd/server.py", line 17, in <module>
    import socketserver
ImportError: No module named socketserver
```

**Comment by quentinhardy** [comment]
I no error anymore, I think this issue can be closed.
