### ISSUE TITLE
mss not found

### ISSUE THREAD

**Issue by loco1101** [n1nj4sec/pupy#544]
```
> run gather/screenshot
[-] Module not found: mss
Traceback (most recent call last):
  File "//pupy/pupy/pupylib/PupyJob.py", line 127, in module_worker
    module.import_dependencies()
  File "/pupy/pupy/pupylib/PupyModule.py", line 314, in import_dependencies
    self.client.load_package(dependencies, new_deps=self.new_deps)
  File "/pupy/pupy/pupylib/PupyClient.py", line 310, in load_package
    raise ValueError('Module not found: {}'.format(e))
ValueError: Module not found: mss
```

uname -a
Linux **** 4.13.0-kali1-amd64 #1 SMP Debian 4.13.13-1kali1 (2017-11-17) x86_64 GNU/Linux

```
pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
AdvancedHTTPServer (2.0.10)
alembic (0.9.3.dev0)
altgraph (0.15)
argcomplete (1.8.1)
argh (0.26.2)
asn1crypto (0.22.0)
attrs (17.3.0)
basemap (1.0.7)
binwalk (2.1.1)
blinker (1.3)
boltons (17.1.0)
Brotli (0.6.0)
buildozer (0.33)
cached-property (1.3.1)
capstone (3.0.4)
Cerberus (1.1)
certifi (2017.7.27.1)
chardet (3.0.4)
click (6.7)
color-print (0.0.2)
colorama (0.3.9)
configparser (3.5.0)
construct (2.8.16)
crcelk (1.1)
cryptography (2.1.3)
cssutils (1.0.2)
cycler (0.10.0)
debtags (2.1)
decorator (4.1.2)
Django (2.0)
dnslib (0.9.7)
dnspython (1.15.0)
docker (2.6.1)
docker-compose (1.17.1)
docker-pycreds (0.2.1)
dockerpty (0.4.1)
docopt (0.6.2)
dropbox (8.5.0)
ecdsa (0.13)
feedparser (5.1.3)
Flask (0.12.2)
future (0.16.0)
geoip2 (2.6.0)
geojson (2.3.0)
gpg (1.9.0)
graphene (1.1.3)
graphene-sqlalchemy (1.1.1)
graphql-core (1.0.1)
graphql-relay (0.4.5)
h2 (2.5.2)
hashID (3.1.4)
hpack (3.0.0)
html2text (2016.9.19)
http-parser (0.8.3)
httplib2 (0.9.2)
hyperframe (4.0.1)
icalendar (3.8)
idna (2.5)
image (1.5.16)
impacket (0.9.15)
iptools (0.6.1)
iso8601 (0.1.11)
itsdangerous (0.24)
Jinja2 (2.9.6)
jsbeautifier (1.6.4)
jsonschema (2.6.0)
kaitaistruct (0.7)
keyboard (0.11.0)
keyring (10.4.0)
keyrings.alt (2.2)
lazyme (0.0.15)
logutils (0.3.5)
macholib (1.9)
Mako (1.0.7)
MarkupSafe (1.0)
matplotlib (2.0.0)
maxminddb (1.3.0)
mitmproxy (2.0.2)
msgpack-python (0.4.8)
mss (3.1.1)
netaddr (0.7.19)
netifaces (0.10.6)
numpy (1.13.3)
olefile (0.44)
paramiko (2.0.2)
passlib (1.7.1)
pathtools (0.1.2)
pefile (2017.11.5)
pexpect (4.3.0)
Pillow (4.3.0)
pip (9.0.1)
pluginbase (0.4)
plumbum (1.6.4)
promise (1.0.1)
psutil (5.4.1)
psycopg2 (2.7.3)
ptyprocess (0.5.2)
pyasn1 (0.1.9)
pyasn1-modules (0.2.1)
PyAutoGUI (0.9.36)
pycairo (1.15.4)
pycrypto (2.6.1)
pycryptodome (3.4.7)
pycurl (7.43.0)
pydispatch (1.1.0)
PyDispatcher (2.0.5)
Pygments (2.2.0)
pygobject (3.26.1)
pyinotify (0.9.6)
PyInstaller (3.3)
pylzma (0.4.9)
PyMsgBox (1.0.6)
PyOpenGL (3.1.0)
pyOpenSSL (16.2.0)
pyotp (2.2.6)
pyparsing (2.1.10)
pyperclip (1.5.32)
pyqtgraph (0.10.0)
PyScreeze (0.1.13)
pyserial (3.4)
python-apt (1.4.0b3+b1)
python-dateutil (2.6.1)
python-debian (0.1.31)
python-debianbts (2.7.1)
python-editor (0.4)
python-pam (1.8.2)
python-xlib (0.20)
PyTweening (1.0.3)
pytz (2017.2)
pyuv (1.4.0)
pyxdg (0.25)
PyYAML (3.12)
reportbug (7.1.7)
requests (2.18.4)
rpyc (3.4.4)
rsa (3.4.2)
ruamel.yaml (0.15.34)
scipy (0.19.1)
SecretStorage (2.3.1)
service-identity (17.0.0)
setuptools (36.7.1)
simplejson (3.12.0)
six (1.11.0)
smoke-zephyr (1.0.2)
sortedcontainers (1.5.7)
SQLAlchemy (1.1.11)
termcolor (1.1.0)
termineter (0.2.7)
texttable (0.9.1)
tinyec (0.3.1)
tornado (4.5.2)
tzlocal (1.4)
unattended-upgrades (0.1)
urllib3 (1.22)
urwid (1.3.1)
virtualenv (15.1.0)
watchdog (0.8.3)
websocket-client (0.44.0)
Werkzeug (0.12.2.dev0)
wheel (0.29.0)
XlsxWriter (0.9.6)
zlib-wrapper (0.1.3)
```

**Comment by loco1101** [comment]
solved by running pip2 install -r pupy/requirements.txt
