### ISSUE TITLE
Connecting payload error.

### ISSUE THREAD

**Issue by PoireWilliams** [n1nj4sec/pupy#550]
Hey,

When I write `connect --host IP` I have this error.

`Traceback (most recent call last):
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 1346, in loop
    self.cmd.cmdloop()
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 272, in cmdloop
    cmd.Cmd.cmdloop(self, intro)
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 646, in do_connect
    self.pupsrv.connect_on_client(arg)
  File "/root/pupy/pupy/pupylib/PupyServer.py", line 400, in connect_on_client
    stream=launcher.iterate().next()
StopIteration`

How can I fix that problem? Thank you!

**Comment by xuxuedong** [comment]
which os do you use?
and
the full command for generating "client"?

**Comment by PoireWilliams** [comment]
@xuxuedong I am using Kali Linux. I am using ./pupygen.py for generating a payload and using ./puppysy.py for client.

**Comment by xuxuedong** [comment]
what's meaing of "using ./puppysy.py for client"?

**Comment by PoireWilliams** [comment]
@xuxuedong I am writing  `./pupysy.py` code on terminal for trying to connect to server.
