### ISSUE TITLE
M2crypto issues

### ISSUE THREAD

**Issue by edenanthony** [n1nj4sec/pupy#565]
Hi,
After try to "pip install -r requirements.txt", This error is happen:

Collecting m2crypto (from -r requirements.txt (line 12))
  Using cached M2Crypto-0.27.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/M2Crypto.egg-info
    writing dependency_links to pip-egg-info/M2Crypto.egg-info/dependency_links.txt
    writing pip-egg-info/M2Crypto.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/M2Crypto.egg-info/top_level.txt
    writing requirements to pip-egg-info/M2Crypto.egg-info/requires.txt
    writing manifest file 'pip-egg-info/M2Crypto.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    INFO:load_grammar:Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
    INFO:load_grammar:Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mjqbkp6c/m2crypto/setup.py", line 350, in <module>
        'clean': Clean
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 186, in run
        self.find_sources()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 209, in find_sources
        mm.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 293, in run
        self.add_defaults()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 322, in add_defaults
        sdist.add_defaults(self)
      File "/usr/lib/python3/dist-packages/setuptools/command/sdist.py", line 132, in add_defaults
        build_ext = self.get_finalized_command('build_ext')
      File "/usr/lib/python3.5/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-build-mjqbkp6c/m2crypto/setup.py", line 161, in finalize_options
        self.include_dirs += _get_additional_includes()
      File "/tmp/pip-build-mjqbkp6c/m2crypto/setup.py", line 51, in _get_additional_includes
        err = [line.lstrip() for line in err.split('\n') if line and line[0] == ' ']
    TypeError: a bytes-like object is required, not 'str'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mjqbkp6c/m2crypto/

Can you help me?

**Comment by edenanthony** [comment]
My os is Ubuntu 16.04

**Comment by lincoln1233** [comment]
Try apt-get install

**Comment by koleror** [comment]
Hello, I have the same issue. 
My problem is I need to install the library using pip on macOS, and, from what I understand, using apt-get on ubuntu + python 3. The problem being I use the same requirements file for both.
FYI, it works on ubuntu 16 + python 2 using pip.

Is there any way to fix the library instead?

**Comment by alxchk** [comment]
Python3 is not supported
