### ISSUE TITLE
Windows Python Payload: PE Memory Execution error

### ISSUE THREAD

**Issue by passwordleak** [n1nj4sec/pupy#577]
Windows 10
Anaconda 5.0.1 Python 2.7

Anaconda python installed on windows, but when I try to run mimikatz (or any other .exe in memory), the follow error occurs: 

```
[!] Error loading package pupwinutils.memexec (pupwinutils/memexec.pyc pkg=False) : Traceback (most recent call last):
  File "pupyimporter", line 328, in load_module
  File "pupwinutils/memexec.py", line 34, in <module>
ImportError: No module named pupymemexec
[-] No module named pupymemexec

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/tmp/pip-build-YWaSOS/rpyc/rpyc/core/protocol.py", line 347, in _dispatch_request
  File "/tmp/pip-build-YWaSOS/rpyc/rpyc/core/protocol.py", line 636, in _handle_callattr
  File "/tmp/pip-build-YWaSOS/rpyc/rpyc/core/service.py", line 115, in __getitem__
  File "", line 526, in exposed_getmodule
  File "pupyimporter", line 363, in load_module
ImportError: No module named pupymemexec
Traceback (most recent call last):
  File "/opt/pupy/pupy/pupylib/PupyJob.py", line 129, in module_worker
    module.run(args)
  File "/opt/pupy/pupy/modules/mimikatz.py", line 70, in run
    output = exec_pe(self, mimikatz_args, path=mimikatz_path, interactive=interactive)
  File "/opt/pupy/pupy/modules/lib/windows/memory_exec.py", line 45, in exec_pe
    'pupwinutils.memexec'
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 213, in method
    return syncreq(_self, consts.HANDLE_CALLATTR, name, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 72, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/opt/pupy/pupy/network/lib/connection.py", line 109, in sync_request
    raise obj
ImportError: No module named pupymemexec

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/tmp/pip-build-YWaSOS/rpyc/rpyc/core/protocol.py", line 347, in _dispatch_request
  File "/tmp/pip-build-YWaSOS/rpyc/rpyc/core/protocol.py", line 636, in _handle_callattr
  File "/tmp/pip-build-YWaSOS/rpyc/rpyc/core/service.py", line 115, in __getitem__
  File "", line 526, in exposed_getmodule
  File "pupyimporter", line 363, in load_module
ImportError: No module named pupymemexec
```

**Comment by n1nj4sec** [comment]
Memory execution needs to load a pyd. pyd currently cannot be loaded using pure python code, so use the exe template and it will work ;)
