### ISSUE TITLE
pupysh.py Address already in use

### ISSUE THREAD

**Issue by grafnugi** [n1nj4sec/pupy#581]
I'm having a problem running pupysh.py on a VPS. Whenever I start it, I get this error, and no clients connect:

"[*] Server started on port 7915 with transport obfs3
>> ERROR:root:[Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/admin/pupy/pupy/pupylib/PupyServer.py", line 452, in run
    igd=self.igd
  File "/home/admin/pupy/pupy/network/lib/servers.py", line 70, in __init__
    ThreadedServer.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 87, in __init__
    self.listener.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use"

**Comment by HorneyAttorney** [comment]
The listening port is already in use..
Try a different port.

**Comment by grafnugi** [comment]
I scanned the port with nmap, and it says it is closed, then when I try to run pupysh.py, i get the same error. how can i tell what is using the port, if indeed it is in use?
