### ISSUE TITLE
Issue starting pupygen.py via ubuntu machine.

### ISSUE THREAD

**Issue by sid-engel** [n1nj4sec/pupy#583]
I've installed all the dependencies, and seem to be stuck on this error.

What can I do here?

```
sid@Sid-Ubuntu:~/Applications/pupy$ python pupygen.py -l
Traceback (most recent call last):
  File "pupygen.py", line 7, in <module>
    from pupylib.utils.network import get_listener_ip, get_listener_port
  File "/home/sid/Applications/pupy/pupylib/__init__.py", line 5, in <module>
    from PupyService import *
  File "/home/sid/Applications/pupy/pupylib/PupyService.py", line 27, in <module>
    from pupylib.PupyCredentials import Credentials
  File "/home/sid/Applications/pupy/pupylib/PupyCredentials.py", line 20, in <module>
    from M2Crypto import X509, EVP, RSA, ASN1, BIO
  File "/home/sid/.local/lib/python2.7/site-packages/M2Crypto/__init__.py", line 26, in <module>
    from M2Crypto import (ASN1, AuthCookie, BIO, BN, DH, DSA, EVP, Engine, Err,
  File "/home/sid/.local/lib/python2.7/site-packages/M2Crypto/ASN1.py", line 15, in <module>
    from M2Crypto import BIO, m2, util
  File "/home/sid/.local/lib/python2.7/site-packages/M2Crypto/BIO.py", line 9, in <module>
    from M2Crypto import m2, six, util
  File "/home/sid/.local/lib/python2.7/site-packages/M2Crypto/m2.py", line 30, in <module>
    from M2Crypto.m2crypto import *
  File "/home/sid/.local/lib/python2.7/site-packages/M2Crypto/m2crypto.py", line 26, in <module>
    _m2crypto = swig_import_helper()
  File "/home/sid/.local/lib/python2.7/site-packages/M2Crypto/m2crypto.py", line 22, in swig_import_helper
    _mod = imp.load_module('_m2crypto', fp, pathname, description)
ImportError: /home/sid/.local/lib/python2.7/site-packages/M2Crypto/_m2crypto.so: undefined symbol: sslv3_method

```

**Comment by muszar** [comment]
Hi, did you found a solution? I have the same issue :(

**Comment by sid-engel** [comment]
I did not, gave up on it. Would love to try again if this ever gets solved.

**Comment by ludoz** [comment]
Hi guys,

I've found the solution on stackoverflow : 

`pip uninstall M2crypto # remove the current error version`
`apt install python-m2crypto -y # install new version from the repo with the good dependencies`

Cheers !

**Comment by muszar** [comment]
@ludoz well done, excellent solution. Thanks

**Comment by b2az** [comment]
@sid-engel Please check the solution provided by @ludoz and it this workaround works, close this issue
