### ISSUE TITLE
raise "ImportError: No module named uuid" error while useing pyinstaller3.0

### ISSUE THREAD

**Issue by pythonwood** [n1nj4sec/pupy#59]
I use pupy:35ec229(HEAD) and pyinstaller:3.0 for a test.

I make binary file with command: "pyinstaller -w -F pp.py".

while 
"python pp.py simple --transport tcp_ssl --host 192.168.x.x:1443" is both ok in ubuntu or xp,
         "dist/pp simple --transport tcp_ssl --host 192.168.x.x:1443" both fail when connecting to server in ubuntu or xp.

output from the server:  (exec: ./pupysh.py --transport tcp_ssl -p 1443)
\>>> 2015-12-27 16:37:20,693 - ERROR - Traceback (most recent call last):
  File "/home/pupy/pupy/pupylib/PupyService.py", line 59, in on_connect
    self.pupy_srv.add_client(self)
  File "/home/pupy/pupy/pupylib/PupyServer.py", line 128, in add_client
    """))
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
ImportError: No module named uuid

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "<string>", line 82, in exposed_execute
  File "<string>", line 2, in execute
  File "<string>", line 4, in <module>
ImportError: No module named uuid

2015-12-27 16:37:25,728 - WARNING - failed to serve client, caught exception : unpack requires a string argument of length 5

**Comment by n1nj4sec** [comment]
you need to embed the python uuid standard module when packaging with pyinstaller. try add an import uuid to pp.py and repackage or add a hidden import to your .spec

**Comment by n1nj4sec** [comment]
you will probably want to include everything in additional_imports.py so import this file instead
