### ISSUE TITLE
ERROR: root : 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by Pyth3rEx** [n1nj4sec/pupy#595]
Setup:
Unbuntu-based distro
Installation and connection made correctly
Port: 443 via SSL

Pupy 1.7-unstable

`
[*] Server started on port 443 with transport ssl
>> ERROR:root:'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/parrot/pupy/pupy/pupylib/PupyServer.py", line 452, in run
    igd=self.igd
  File "/home/parrot/pupy/pupy/network/lib/servers.py", line 80, in __init__
    self.igd.AddPortMapping(self.port, 'TCP', self.port)
  File "/home/parrot/pupy/pupy/network/lib/igd.py", line 298, in AddPortMapping
    self.ctrlURL, upnp_method, sendArgs
  File "/home/parrot/pupy/pupy/network/lib/igd.py", line 617, in sendSOAP
    err_code, err_desc = self._parseErrMsg(e.read())
  File "/home/parrot/pupy/pupy/network/lib/igd.py", line 189, in _parseErrMsg
    return (err_code.text, err_desc.text)
AttributeError: 'NoneType' object has no attribute 'text'
`

**Comment by Pyth3rEx** [comment]
so using 'Ctrl+c' seems to just bypass the error. I'll do some testing to see if it affects the program in any way...
