### ISSUE TITLE
Migrate command gives traceback

### ISSUE THREAD

**Issue by artagel** [n1nj4sec/pupy#6]
```
>> migrate 4088
[+] looking for configured connect back address ...
[+] address configured is 10.0.1.62:443 ...
[+] looking for process 4088 architecture ...
[-] cannot import name _common

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "rpyc\core\protocol.pyc", line 305, in _dispatch_request
  File "rpyc\core\protocol.pyc", line 547, in _handle_callattr
  File "rpyc\core\service.pyc", line 118, in __getitem__
  File "<string>", line 58, in exposed_getmodule
  File "<string>", line 97, in load_module
ImportError: cannot import name _common
```

**Comment by byt3bl33d3r** [comment]
@artagel that's related to #3 since the migrate module uses the psutils library
