### ISSUE TITLE
Have problem with passing Argument

### ISSUE THREAD

**Issue by crack3r85** [n1nj4sec/pupy#60]
Hi n1nj4sec,

I am new to pupy and have an issue. When i try to use some module that need to pass an argument I get this error message. Please have me with this

>> run keylogger start
Traceback (most recent call last):
  File "pupysh.py", line 74, in <module>
    pcmd.cmdloop()
  File "/root/Downloads/pupy-master/pupy/pupylib/PupyCmd.py", line 273, in cmdloop
    cmd.Cmd.cmdloop(self, intro)
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/root/Downloads/pupy-master/pupy/pupylib/PupyCmd.py", line 590, in do_run
    pj.start(args)
  File "/root/Downloads/pupy-master/pupy/pupylib/PupyJob.py", line 137, in start
    comp, comp_exp= m.is_compatible()
TypeError: 'NoneType' object is not iterable

**Comment by n1nj4sec** [comment]
Hello, thank you for your report. Do you still have the issue ?

**Comment by crack3r85** [comment]
Hi n1nj4sec, it work excellent now! Thank you for your quick response
