### ISSUE TITLE
Windows RDP Issue

### ISSUE THREAD

**Issue by xchirrix** [n1nj4sec/pupy#607]
I'm Triying to use windows rdp module but I'm having this error

>> run windows/admin/rdp remote -t 192.168.252.191 -u IEUser
[-] [('SSL routines', 'SSL_CTX_set_cipher_list', 'no cipher match')]

========= Remote Traceback (1) =========
Traceback (most recent call last):
Error: [('SSL routines', 'SSL_CTX_set_cipher_list', 'no cipher match')]
Traceback (most recent call last):
  File "/home/pentester/Documents/tools/pupy/pupy/pupylib/PupyJob.py", line 129, in module_worker
    module.run(args)
  File "/home/pentester/Documents/tools/pupy/pupy/modules/rdp.py", line 73, in run
    host, args.username, args.password, args.domain, args.hashes
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 199, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 72, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/home/pentester/Documents/tools/pupy/pupy/network/lib/connection.py", line 109, in sync_request
    raise obj
OpenSSL.SSL.Error: [('SSL routines', 'SSL_CTX_set_cipher_list', 'no cipher match')]

========= Remote Traceback (1) =========
Traceback (most recent call last):
Error: [('SSL routines', 'SSL_CTX_set_cipher_list', 'no cipher match')]

**Comment by glides** [comment]
You didn't specify a password for the user in your command.
