### ISSUE TITLE
Value must be precomputed hash

### ISSUE THREAD

**Issue by matty45** [n1nj4sec/pupy#611]
```
/pupygen.py
[!] required argument missing, automatically adding parameter --host 192.168.1.218:443 from local or external ip address
[+] Generate client: windows/x86
[C] launcher: connect
[C] launcher_args: ['--host', '192.168.1.218:443', '-t', 'ssl']
[C] debug: False
WARNING:root:Generating credentials to /home/user/Desktop/pupy/pupy/crypto/credentials.py
...........++
..................++
.......................................................................++
............................................++
..................++++++
................++++++
..........++++++
...++++++
................++++++
............++++++
.++++++
.........................................++++++
..............++++++
..++++++
ERROR:root:value must be precomputed hash
Traceback (most recent call last):
  File "./pupygen.py", line 691, in <module>
    pupygen(parser.parse_args(), config)
  File "./pupygen.py", line 584, in pupygen
    compressed=not ( args.uncompressed or args.packer )
  File "./pupygen.py", line 392, in generate_binary_from_template
    return generator(template, config, compressed), filename, makex
  File "./pupygen.py", line 56, in get_edit_binary
    new_conf = marshal.dumps(compile(get_raw_conf(conf), '<config>', 'exec'))
  File "./pupygen.py", line 79, in get_raw_conf
    credentials = Credentials(role='client')
  File "/home/user/Desktop/pupy/pupy/pupylib/PupyCredentials.py", line 182, in __init__
    self._generate(password=password, configfile=configfile)
  File "/home/user/Desktop/pupy/pupy/pupylib/PupyCredentials.py", line 354, in _generate
    SSL_CA_PRIVATE_KEY, SSL_CA_CERTIFICATE, CAKEY, CACERT = self._generate_ssl_ca()
  File "/home/user/Desktop/pupy/pupy/pupylib/PupyCredentials.py", line 293, in _generate_ssl_ca
    cert.add_ext(X509.new_extension('subjectKeyIdentifier', cert.get_fingerprint()))
  File "/home/user/.local/lib/python2.7/site-packages/M2Crypto/X509.py", line 45, in new_extension
    raise ValueError('value must be precomputed hash')
ValueError: value must be precomputed hash
value must be precomputed hash
```

Anyone know what is causing this error?

**Comment by matty45** [comment]
Duplicate of issue #609
