### ISSUE TITLE
WARNING:scapy.loading:Cannot read wireshark manuf database

### ISSUE THREAD

**Issue by xcrypt999** [n1nj4sec/pupy#620]
I upgraded python to 2.7.15, then I ran "pip install -r requirements.txt" and finally I got an error when running pupysh.py

[I] Credentials password:
WARNING:scapy.loading:Cannot read wireshark manuf database
[*] [+] Starting webserver on http://127.0.0.1:9000
>>
            _____                    _       _ _
 ___ ___   |  _  |_ _ ___ _ _    ___| |_ ___| | |   ___ ___
|___|___|  |   __| | | . | | |  |_ -|   | -_| | |  |___|___|
           |__|  |___|  _|_  |  |___|_|_|___|_|_|
                     |_| |___|

                   v1.7-unstable (Sep 15 2017)

Author:           Nicolas VERDIER  < @n1nj4sec > (contact@n1nj4.eu)
Bleeding edge:    https://github.com/n1nj4sec/pupy

[*] Server started on port 443 with transport ssl
>> Exception in thread Thread-8:
Traceback (most recent call last):
  File "/root/.pyenv/versions/2.7.15/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/.pyenv/versions/2.7.15/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/pupy/network/lib/servers.py", line 119, in _setup_connection
    config=config
  File "/opt/pupy/network/lib/connection.py", line 35, in __init__
    Connection.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument '_lazy'

Exception AttributeError: "'PupyConnection' object has no attribute '_closed'" in <object repr() failed> ignored
Exception in thread Thread-28:
Traceback (most recent call last):

**Comment by spenserq** [comment]
I have the same problem when the client tries to connect to my server.
Python version at server 2.7.15

Client:
`root@client:/root/Desktop# ./pupy_1pYyfL.py 
Exception AttributeError: "'PupyConnection' object has no attribute '_closed'" in <object repr() failed> ignored`

Server:
`>> Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/pupy/pupy/network/lib/servers.py", line 119, in _setup_connection
    config=config
  File "/usr/share/pupy/pupy/network/lib/connection.py", line 35, in __init__
    Connection.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument '_lazy'
`

**Comment by thefare** [comment]
me too

**Comment by spenserq** [comment]
Hi, ‚thefore’ you need to uninstall newest Rpyc library and install old one == 3.4.4 - then all work great :)
https://github.com/n1nj4sec/pupy/issues/622
