### ISSUE TITLE
getting an arror when packaging an apk

### ISSUE THREAD

**Issue by Kyr4loO** [n1nj4sec/pupy#621]
ERROR:root:Command 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '/tmp/tmp_pupy_RDj9f5' pupy_key' returned non-zero exit status 1
Traceback (most recent call last):
  File "./pupygen.py", line 691, in <module>
    pupygen(parser.parse_args(), config)
  File "./pupygen.py", line 584, in pupygen
    compressed=not ( args.uncompressed or args.packer )
  File "./pupygen.py", line 392, in generate_binary_from_template
    return generator(template, config, compressed), filename, makex
  File "./pupygen.py", line 217, in get_edit_apk
    res=subprocess.check_output("jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '%s' pupy_key"%tempapk, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '/tmp/tmp_pupy_RDj9f5' pupy_key' returned non-zero exit status 1
Command 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '/tmp/tmp_pupy_RDj9f5' pupy_key' returned non-zero exit status 1

**Comment by AlphaMufasaOmega** [comment]
i believe this has to do with reinstalling the jdk 10 or jarsigner specifically try these instructions https://linuxhint.com/install-openjdk-10-debian-9-stretch/ or install jarsigner individually using command line  terminal... i had this error and ifixed it. i manually installed each package for requirements.txt and my pupy setup is more stable than the recent docker image i think... at least so far :/

**Comment by AlphaMufasaOmega** [comment]
maybe delete credentials.py in pupy/pupy/crypto

**Comment by AlphaMufasaOmega** [comment]
using sudo rm -rf credentials.py
