### ISSUE TITLE
listener is not working 

### ISSUE THREAD

**Issue by moyoussry** [n1nj4sec/pupy#622]
root@root:~/pupy/pupy# python2.7 pupysh.py -p 1177
[I] Credentials password: 
[*] [+] Starting webserver on http://127.0.0.1:9000
>> 
            _____                    _       _ _
 ___ ___   |  _  |_ _ ___ _ _    ___| |_ ___| | |   ___ ___
|___|___|  |   __| | | . | | |  |_ -|   | -_| | |  |___|___|
           |__|  |___|  _|_  |  |___|_|_|___|_|_|
                     |_| |___|

                   v1.7-unstable (Sep 15 2017)

Author:           Nicolas VERDIER  < @n1nj4sec > (contact@n1nj4.eu)
Bleeding edge:    https://github.com/n1nj4sec/pupy

[*] Server started on port 1177 with transport ssl
>> Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/pupy/pupy/network/lib/servers.py", line 119, in _setup_connection
    config=config
  File "/root/pupy/pupy/network/lib/connection.py", line 35, in __init__
    Connection.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument '_lazy'

Exception AttributeError: "'PupyConnection' object has no attribute '_closed'" in <object repr() failed> ignored
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/pupy/pupy/network/lib/servers.py", line 119, in _setup_connection
    config=config
  File "/root/pupy/pupy/network/lib/connection.py", line 35, in __init__
    Connection.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument '_lazy'

Exception AttributeError: "'PupyConnection' object has no attribute '_closed'" in <object repr() failed> ignored
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/pupy/pupy/network/lib/servers.py", line 119, in _setup_connection
    config=config
  File "/root/pupy/pupy/network/lib/connection.py", line 35, in __init__
    Connection.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument '_lazy'

Exception AttributeError: "'PupyConnection' object has no attribute '_closed'" in <object repr() failed> ignored
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/pupy/pupy/network/lib/servers.py", line 119, in _setup_connection
    config=config
  File "/root/pupy/pupy/network/lib/connection.py", line 35, in __init__
    Connection.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument '_lazy'

Exception AttributeError: "'PupyConnection' object has no attribute '_closed'" in <object repr() failed> ignored

**Comment by alxchk** [comment]
Rpyc has been updated to with incompatible API change. 3.4.4 should be used, as last compatible

**Comment by backmashine** [comment]
Downgrade rpyc helped, thanks
