### ISSUE TITLE
Error : value must be precomputed hash

### ISSUE THREAD

**Issue by Maximevilla** [n1nj4sec/pupy#631]
Someone knows where this error come from ?

`[titi@lap pupy]$ python2 ./pupygen.py -f py connect --transport ssl --host 192.168.1.1
WARNING:root:Generating credentials to /home/titi/src/pupy/pupy/crypto/credentials.py
......................................................................................++
...........................................................................................................++
...............................................................................................++
....++
....++++++
..........++++++
.............++++++
..++++++
......++++++
..++++++
.....................++++++
.....++++++
.........++++++
.............................................................................++++++
ERROR:root:value must be precomputed hash
Traceback (most recent call last):
  File "./pupygen.py", line 691, in <module>
    pupygen(parser.parse_args(), config)
  File "./pupygen.py", line 636, in pupygen
    packed_payload=pack_py_payload(get_raw_conf(conf, verbose=True))
  File "./pupygen.py", line 79, in get_raw_conf
    credentials = Credentials(role='client')
  File "/home/titi/src/pupy/pupy/pupylib/PupyCredentials.py", line 182, in __init__
    self._generate(password=password, configfile=configfile)
  File "/home/titi/src/pupy/pupy/pupylib/PupyCredentials.py", line 354, in _generate
    SSL_CA_PRIVATE_KEY, SSL_CA_CERTIFICATE, CAKEY, CACERT = self._generate_ssl_ca()
  File "/home/titi/src/pupy/pupy/pupylib/PupyCredentials.py", line 293, in _generate_ssl_ca
    cert.add_ext(X509.new_extension('subjectKeyIdentifier', cert.get_fingerprint()))
  File "/usr/lib/python2.7/site-packages/M2Crypto/X509.py", line 45, in new_extension
    raise ValueError('value must be precomputed hash')
ValueError: value must be precomputed hash
value must be precomputed hash
`

Thanks

**Comment by alxchk** [comment]
https://github.com/n1nj4sec/pupy/pull/610
