### ISSUE TITLE
No module named rpyc.core.service

### ISSUE THREAD

**Issue by Staszka** [n1nj4sec/pupy#638]
root@STAHU:~/pupy/pupy# ./pupygen.py
Traceback (most recent call last):
  File "./pupygen.py", line 14, in <module>
    from pupylib.utils.network import get_listener_ip, get_listener_port
  File "/root/pupy/pupy/pupylib/__init__.py", line 18, in <module>
    from PupyService import *
  File "/root/pupy/pupy/pupylib/PupyService.py", line 17, in <module>
    import rpyc.core.service
ImportError: No module named rpyc.core.service

What i must do?

**Comment by alxchk** [comment]
Looks like something wrong with pycryprodome. Try to reinstall it (force if required)

**Comment by AlphaMufasaOmega** [comment]
I jave a similiar problem when I am trying to generate a payload... i reinstalled jdk-10.0.2 but it still isn't working I get the following:
```
/bin/sh: 1: jarsigner: not found
[-] payload generation failed: Command 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '/tmp/tmp_pupy_vHVQbg' pupy_key' returned non-zero exit status 127

```

**Comment by AlphaMufasaOmega** [comment]
I thin I have t o reinstall jarsigner manually i solved this problem once I think...
