### ISSUE TITLE
TypeError: runLaZagne() got an unexpected keyword argument 'category_choosed'

### ISSUE THREAD

**Issue by passwordleak** [n1nj4sec/pupy#648]
Tried to run lazagne on windows 10 and I get the following error:

```
>> run lazagne
[date redacted]| runLaZagne() got an unexpected keyword argument 'category_choosed'

========= Remote Traceback (1) =========
Traceback (most recent call last):
TypeError: runLaZagne() got an unexpected keyword argument 'category_choosed'
Traceback (most recent call last):
  File "/opt/pupy/pupylib/PupyJob.py", line 161, in module_worker
    module.run(self.args)
  File "/opt/pupy/modules/lazagne.py", line 76, in run
    category_choosed=args.category, raise_on_exception=False))
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 199, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 72, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/opt/pupy/network/lib/connection.py", line 381, in sync_request
    raise obj
TypeError: runLaZagne() got an unexpected keyword argument 'category_choosed'

========= Remote Traceback (1) =========
Traceback (most recent call last):
TypeError: runLaZagne() got an unexpected keyword argument 'category_choosed'

[-] runLaZagne() got an unexpected keyword argument 'category_choosed'

========= Remote Traceback (1) =========
Traceback (most recent call last):
TypeError: runLaZagne() got an unexpected keyword argument 'category_choosed'
```

**Comment by AlessandroZ** [comment]
You use a version too recent of lazagne that is not yet compatible with your pupy version. Don't upgrade manually git submodules.
