### ISSUE TITLE
./create-workspace.py fatal errors

### ISSUE THREAD

**Issue by edenanthony** [n1nj4sec/pupy#658]
Hello Dear,

Errors occurred : 

Generating code
   Creating library ../../pupy/payload_templates/pupyx64d.unc.lib and object ../../pupy/payload_templates/pupyx64d.unc.exp
Generating code
Z:\build\workspace\project\client\sources\pupy.c : fatal error C1002: compiler is out of heap space in pass 2
Z:\build\workspace\project\client\sources\pupy.c : fatal error C1002: compiler is out of heap space in pass 2
LINK : fatal error LNK1257: code generation failed
LINK : fatal error LNK1257: code generation failed
Makefile:128: recipe for target '../../pupy/payload_templates/pupyx64d.unc.dll' failed
Makefile:125: recipe for target '../../pupy/payload_templates/pupyx64d.unc.exe' failed
make: *** [../../pupy/payload_templates/pupyx64d.unc.dll] Error 2
make: *** Waiting for unfinished jobs....
make: *** [../../pupy/payload_templates/pupyx64d.unc.exe] Error 2
rm -f *.obj
rm -f *.pyo
rm -f *.pyc
rm -f resources/bootloader.pyc
rm -f resources/*.c
rm -f resources/win64/*.c
rm -f _memimporter.obj MyLoadLibrary.obj Python-dynload.obj pupy_load.obj pupy.obj base_inject.obj MemoryModule.obj actctx.obj list.obj thread.obj remote_thread.obj LoadLibraryR.obj
rm -f revision.h
rm -f import-tab.c
rm -f import-tab.h
rm -f revision.h
rm -rf resources
[-] pupyx64d.unc.dll - failed
[-] pupyx64d.unc.exe - failed
[-] pupyx64.unc.dll - failed
[-] pupyx64.unc.exe - failed
[-] pupyx86.unc.dll - failed
[-] pupyx86.unc.exe - failed
[-] Build failed
Traceback (most recent call last):
  File "./create-workspace.py", line 168, in <module>
    main()
  File "./create-workspace.py", line 78, in main
    ], env=env, cwd=os.path.join(args.pupy_git_folder, 'client'))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/pupy/client/build-docker.sh']' returned non-zero exit status 1

How to solve it?

Tnx

**Comment by alxchk** [comment]
```
Z:\build\workspace\project\client\sources\pupy.c : fatal error C1002: compiler is out of heap space in pass 2
```

Looks like issue with free memory. Do you have enough?

**Comment by n1nj4sec** [comment]
If you don't want to rebuild your payloads, use -DG to avoid rebuilding everything

**Comment by edenanthony** [comment]
Thanks @alxchk 
I have upgraded my server to 2048MB Ram, but pupy issued new Error

Here's the log:
--------
virtual memory exhausted: Cannot allocate memory
make: *** [pupy.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from pupy_load.c:41:
../lzma/lzmaunpack.c: In function 'lzmaunpack':
../lzma/lzmaunpack.c:76: warning: assignment discards qualifiers from pointer target type
pupy_load.c: At top level:
../lzma/lzmaunpack.c:101: warning: 'PyDict_lzmaunpack' defined but not used
Traceback (most recent call last):
  File "./create-workspace.py", line 168, in <module>
    main()
  File "./create-workspace.py", line 78, in main
    ], env=env, cwd=os.path.join(args.pupy_git_folder, 'client'))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/pupy/client/build-docker.sh']' returned non-zero exit status 2
----------
It would be better to add requirement list in your first page, What's your idea @n1nj4sec ?
