### ISSUE TITLE
Scramblesuit transport fails - no HMAC

### ISSUE THREAD

**Issue by platdrag** [n1nj4sec/pupy#66]
Below's the log from the server. should i generate the HMAC when generating the payload? there's no documentation...

>> 2016-02-15 11:12:44,820 - INFO  - server started on [0.0.0.0]:1235
2016-02-15 11:12:58,116 - INFO  - accepted 79.182.111.135:25463
2016-02-15 11:12:58,116 - DEBUG - Initialising ScrambleSuit.
2016-02-15 11:12:58,117 - INFO  - Attempting to load the server's state file from memory.
2016-02-15 11:12:58,117 - INFO  - The server's state file does not exist (yet).
2016-02-15 11:12:58,117 - INFO  - Generating parameters for the server's state file.
2016-02-15 11:12:58,117 - DEBUG - Dumping probability distribution.
2016-02-15 11:12:58,117 - DEBUG - P(674) = 0.059
2016-02-15 11:12:58,117 - DEBUG - P(1158) = 0.093
2016-02-15 11:12:58,117 - DEBUG - P(176) = 0.796
2016-02-15 11:12:58,117 - DEBUG - P(122) = 0.025
2016-02-15 11:12:58,117 - DEBUG - P(763) = 0.013
2016-02-15 11:12:58,117 - DEBUG - Dumping probability distribution.
2016-02-15 11:12:58,117 - DEBUG - P(0.00153246526226) = 0.059
2016-02-15 11:12:58,118 - DEBUG - P(0.00318014526403) = 0.093
2016-02-15 11:12:58,118 - DEBUG - P(0.00279946175613) = 0.025
2016-02-15 11:12:58,118 - DEBUG - P(0.00327026925494) = 0.796
2016-02-15 11:12:58,118 - DEBUG - P(4.60356859265e-05) = 0.013
2016-02-15 11:12:58,119 - DEBUG - Switching to state ST_WAIT_FOR_AUTH.
2016-02-15 11:12:58,119 - DEBUG - Initialising AES-CTR instance.
2016-02-15 11:12:58,119 - DEBUG - Initialising AES-CTR instance.
2016-02-15 11:12:58,119 - DEBUG - Buffered 14 bytes of outgoing data.
2016-02-15 11:12:58,190 - DEBUG - Attempting to decrypt and verify ticket.
2016-02-15 11:12:58,190 - DEBUG - Attempting to extract the remote machine's UniformDH public key out of 1018 bytes of data.
2016-02-15 11:12:58,190 - DEBUG - Successfully located the mark.
2016-02-15 11:12:58,191 - DEBUG - HMAC invalid.  Trying next epoch value.
2016-02-15 11:12:58,191 - DEBUG - HMAC invalid.  Trying next epoch value.
2016-02-15 11:12:58,191 - DEBUG - HMAC invalid.  Trying next epoch value.
2016-02-15 11:12:58,191 - WARNING - Could not verify the authentication message's HMAC.
2016-02-15 11:12:58,191 - DEBUG - Authentication unsuccessful so far.  Waiting for more data.
2016-02-15 11:13:08,189 - DEBUG - Traceback (most recent call last):
  File "/home/ec2-user/pupy/pupy/network/streams.py", line 87, in read
    self._read()
  File "/home/ec2-user/pupy/pupy/network/streams.py", line 58, in _read
    raise EOFError("connection closed by peer")
EOFError: connection closed by peer

2016-02-15 11:13:08,190 - ERROR - Traceback (most recent call last):
  File "/home/ec2-user/pupy/pupy/pupylib/PupyService.py", line 49, in on_connect
    self.namespace=self._conn.root.namespace
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 467, in root
    self._remote_root = self.sync_request(consts.HANDLE_GETROOT)
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 438, in sync_request
    self.serve(0.1)
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 387, in serve
    data = self._recv(timeout, wait_for_lock = True)
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 345, in _recv
    data = self._channel.recv()
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/channel.py", line 51, in recv
    length, compressed = self.FRAME_HEADER.unpack(header)
error: unpack requires a string argument of length 5

2016-02-15 11:13:08,190 - WARNING - failed to serve client, caught exception : stream has been closed

**Comment by n1nj4sec** [comment]
The hmac is hardcoded so you don't need to change it (if you do you need to change it on both the client and the server).
Can you send me the pupygen command line and the output and the pupysh command line you used ? There is no documentation but it's pretty intuitive if you read the wiki you should be able to make it work

**Comment by platdrag** [comment]
generating the payload:
./pupygen.py -o pupy_x86_32_scramblesuit_1235.exe -t exe_x86 auto_proxy --transport scramblesuit --host XXX.XXX.XXX.XXX:1235

running the server:
./pupysh.py --transport scramblesuit --port 1235


also tried with simple instead of auto_proxy... no difference

**Comment by n1nj4sec** [comment]
it works for me, did you tried locally ? As I can see in your traceback, you are using this on internet. Perhaps someone is tampering with your traffic ?

**Comment by platdrag** [comment]
I dunno this is the case. i own both machines and no network devices in the middle. 
i'll try it on the local LAN just in case and report back.
Just to educate, what kind of tampering would result in changing the HMAC?
