### ISSUE TITLE
Connect frequency to high?

### ISSUE THREAD

**Issue by Zorilixer** [n1nj4sec/pupy#663]
Why is the (re)connect frequency that high?
Certainly, if no Pupy endpoint is available, then the connect frequency should drop, i.e., connection-attempts should happen more rarely after some time.

https://github.com/n1nj4sec/pupy/blob/e986a03124ae2235d145629c96e4eb82a7accc1c/pupy/pp.py#L669

- For the first 120 attempts the wait time is < 1 sec.
- The next 200 attempts the wait time is roughly 3 < x < 5 sec.
- After that the wait time is 15 < x < 30 sec.

I would suggest to change that to less frequent.
E.g., drop the division by 10 and adjust 120 to 10 and 320 to 50.

What do you think?

**Comment by alxchk** [comment]
There is PR "beacon delay". You can try to check is it works and adopt to current upstream. It's better to have this configurable somehow. Adding this parameters to config is better option IMHO

**Comment by Strazzom** [comment]
I would suggest a default setting, as well as a way to configure it per client. This is the way Empire handles it.

**Comment by Zorilixer** [comment]
Thanks. Your solution approach is better. But it seems to has issues.

`gen ... -d 10 10 30 connect  ...` 

`` ` 
[-] payload generation failed: sequence item 0: expected string, list found
Traceback (most recent call last):
  File "/opt/pupy/pupy.git/pupy/commands/gen.py", line 133, in do
    output = pupygen.pupygen(args, config, server, handler.display)
  File "/opt/pupy/pupy.git/pupy/pupygen.py", line 657, in pupygen
    compressed=not (args.uncompressed or args.packer)
  File "/opt/pupy/pupy.git/pupy/pupygen.py", line 440, in generate_binary_from_template
    } for k,v in config.iteritems() if v]
TypeError: sequence item 0: expected string, list found
` ` ` 
argparse seems to store the delay list as list type which does not work for iteritems.
Perhaps store it as a string, then later split it?
