### ISSUE TITLE
APK Generation

### ISSUE THREAD

**Issue by SammySet007** [n1nj4sec/pupy#665]
Hi, I have Pupy running in a non docker environment. Windows payloads are working however when I try to generate an Android payload I get errors relating to the jarsigner

```
> `$ pupygen -f client -O android -o /home/USER/android_rat.apk connect --host REMOVED:8443
> [+] Generate client: android/x86
> [C] launcher: connect
> [C] launcher_args: ['--host', 'REMOVED:8443']
> [C] cid: 0x4fd723cdL
> [C] debug: False
> [I] Credentials password:
> [+] Required credentials (found):
> [+] SSL_BIND_CERT, SSL_CA_CERT, SSL_CLIENT_CERT, SSL_BIND_KEY, SSL_CLIENT_KEY
> [+] generating PY payload ...
> [+] packaging the apk ... (can take 10-20 seconds)
> ERROR:pupy.gen:Command 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '/tmp/tmp_pupy_rXcecv' pupy_key' returned non-zero exit status 1
> Traceback (most recent call last):
>   File "/home/USER/pupy/pupy/pupygen.py", line 740, in <module>
>     pupygen(parser.parse_args(), config)
>   File "/home/USER/pupy/pupy/pupygen.py", line 622, in pupygen
>     compressed=not (args.uncompressed or args.packer)
>   File "/home/USER/pupy/pupy/pupygen.py", line 415, in generate_binary_from_template
>     return generator(template, config, compressed, debug), filename, makex
>   File "/home/USER/pupy/pupy/pupygen.py", line 241, in get_edit_apk
>     res=subprocess.check_output("jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '%s' pupy_key"%tempapk, shell=True)
>   File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> CalledProcessError: Command 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '/tmp/tmp_pupy_rXcecv' pupy_key' returned non-zero exit status 1
> Command 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '/tmp/tmp_pupy_rXcecv' pupy_key' returned non-zero exit status 1`
```

Java 10 is running and if i run jarsigner it is detected by the OS (Ubuntu 16.04)

I have  attached below the exact code I have run for installing

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install python-minimal git python-dev python-pip tcpdump python-virtualenv libssl-dev libffi-dev default-jdk swig
sudo pip install m2crypto
git clone --recursive https://github.com/n1nj4sec/pupy
cd pupy
python create-workspace.py -DG pupyw
export PATH=$PATH:~/.local/bin
```
Im convinced its a module or something simple I am missing - any advice would be great.

**Comment by SammySet007** [comment]
Also just repeated the above in Debian 9 with the same error code.

**Comment by alxchk** [comment]
Default pupy's initialization does not generate key for signing APKs. So this `crypto/pupy-apk-release-key.keystore` likely either missing or empty

**Comment by SammySet007** [comment]
Many thanks, I generated a signed key using the method below 
`keytool -genkey -v -keystore pupy-apk-release-key.keystore`
Still get the same error. Is there a specific way to generate the keys?
