### ISSUE TITLE
UnboundLocalError when run python payload

### ISSUE THREAD

**Issue by j3ssie** [n1nj4sec/pupy#675]
I created python payload using this command below
```
gen -f py -A x64 --os linux -o /tmp/shells/ooo
```

but when I run it it's pop up this Error:
```
root@cpu1024:/tmp# python ooo
WARNING:pupy.network.pss:Datagram based stream is not available: KCP missing
ERROR:pupy.network:Transport ec4 disabled: cannot import name EC4TransportServer
Traceback (most recent call last):
 File "network/lib/__init__.py", line 44, in <module>
ImportError: cannot import name EC4TransportServer
ERROR:pupy.network:Transport ecm disabled: cannot import name ECMTransportServer
Traceback (most recent call last):
 File "network/lib/__init__.py", line 51, in <module>
ImportError: cannot import name ECMTransportServer
ERROR:root:cannot import name DNSCncLauncher: DNSCncLauncher disabled
Traceback (most recent call last):
 File "network/conf.py", line 20, in <module>
ImportError: cannot import name DNSCncLauncher
ERROR:root:cannot import name DNSCncLauncher: DNSCncLauncher disabled
Traceback (most recent call last):
 File "network/conf.py", line 20, in <module>
ImportError: cannot import name DNSCncLauncher
ERROR:root:timed out
Traceback (most recent call last):
 File "network/lib/launchers/connect.py", line 84, in iterate
 File "network/lib/clients.py", line 137, in connect
 File "network/lib/clients.py", line 50, in connect
 File "/usr/lib/python2.7/socket.py", line 228, in meth
   return getattr(self._sock,name)(*args)
timeout: timed out
Traceback (most recent call last):
 File "ooo", line 4, in <module>
   e0\x048UCr\x00\x01\x18d]$\xb2.A\xad &\xfbW\xdd\xe0|\xe2\x13\xcc\x1a\xf7\xd1\xf2\xc0\xfd\x99K\xaf\x85h\x9b\xd2\xae"P+\x01$\x0b\x16\xa4\xd5\xd0}\xe2\xb0\xf8\xce\xb3J%L\xae\xd4;\xf3\xb7\xeaw\xa3\x1as\x05Io\x8b\x1e&\x94\xa2%\xf6\x8cD\x8fg|\xa2\x10\xbd\x987E\x8f\xea3\xf5\x1f\xeb\xd5(\x8e\xa6\x18E\x8dKA\xf4]\xd4H\x08\xea*aU\xda\x8a\xcd\x7f\xecF\x9c\xc3'))
 File "", line 922, in <module>

 File "", line 847, in main

UnboundLocalError: local variable 'time' referenced before assignment
```

I running lastest version of pupy and my victim machine is Debian 9.

**Comment by bhuvan2099** [comment]
Getting the same error on centos 7. Any ideas how to resolve this?

**Comment by helpmeplease4** [comment]
Im getting the same error "ImportError: cannot import Name to_bytes" on a macbook air
