### ISSUE TITLE
exec with escaped character should have exception handled properly

### ISSUE THREAD

**Issue by artagel** [n1nj4sec/pupy#7]
```
>> exec cd C:\
Traceback (most recent call last):
  File "./pupysh.py", line 62, in <module>
    pcmd.cmdloop()
  File "/root/working/pupy/pupy/pupylib/PupyCmd.py", line 219, in cmdloop
    cmd.Cmd.cmdloop(self, intro)
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 220, in onecmd
    return self.default(line)
  File "/root/working/pupy/pupy/pupylib/PupyCmd.py", line 192, in default
    modargs,left=arg_parser.parse_known_args(shlex.split(tab[1]))
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 191, in read_token
    raise ValueError, "No escaped character"
ValueError: No escaped character
```

**Comment by n1nj4sec** [comment]
It is but you missuse it. exec uses argparse 
>> exec
usage: shell_exec [-h] argument [argument ...]
shell_exec: error: too few arguments

so you need to add quotes like on a unix shell
>> exec 'cd C:\'
