### ISSUE TITLE
Kali Linux pupy problem

### ISSUE THREAD

**Issue by GoldLine** [n1nj4sec/pupy#701]
connecting to my domain here:port using transport ssl ...
using client options: {}
using transports options: {}
Traceback (most recent call last):
File "f:183", line 84, in iterate
File "f:14c", line 137, in connect
File "f:14c", line 50, in connect
File "f:1f7", line 228, in meth
error: [Errno 111] Connection refused
------
lin debug

**Comment by alxchk** [comment]
Looks like connectivity issue. Check your network

**Comment by GoldLine** [comment]
Ok the problem now fix but I got a new problem xD

EOF occurred in violation of protocol (_ssl.c:726
Traceback (most recent call last):
File "f:183", line 84, in iterate
File "f:14c", line 174, in connect
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:726)

**Comment by quentinhardy** [comment]
I think this issue can be closed now. The bug fix is https://github.com/n1nj4sec/pupy/pull/702. Thank you @n1nj4sec for the fix.
