### ISSUE TITLE
Poster module

### ISSUE THREAD

**Issue by edenanthony** [n1nj4sec/pupy#713]
Hi ,
How to fix this error?
Tanks for your attention.
----------------------------------------
root@Anthony:/opt/pupy# pupygen -l
No handlers could be found for logger "pupy.network.pss"
ERROR:root:No module named poster.streaminghttp: AutoProxyLauncher disabled
Traceback (most recent call last):
  File "/opt/pupy/pupy/network/conf.py", line 81, in <module>
    from .lib.launchers.auto_proxy import AutoProxyLauncher
  File "/opt/pupy/pupy/network/lib/launchers/auto_proxy.py", line 13, in <module>
    from ..proxies import get_proxies, find_default_proxy
  File "/opt/pupy/pupy/network/lib/proxies.py", line 375, in <module>
    from network.lib.tinyhttp import HTTP
  File "/opt/pupy/pupy/network/lib/tinyhttp.py", line 17, in <module>
    from poster.streaminghttp import StreamingHTTPConnection, StreamingHTTPSConnection
ImportError: No module named poster.streaminghttp
ERROR:root:No module named poster.streaminghttp: DNSCncLauncher disabled
Traceback (most recent call last):
  File "/opt/pupy/pupy/network/conf.py", line 93, in <module>
    from .lib.launchers.dnscnc import DNSCncLauncher
  File "/opt/pupy/pupy/network/lib/launchers/dnscnc.py", line 10, in <module>
    from ..proxies import get_proxies, find_default_proxy
  File "/opt/pupy/pupy/network/lib/proxies.py", line 375, in <module>
    from network.lib.tinyhttp import HTTP
  File "/opt/pupy/pupy/network/lib/tinyhttp.py", line 17, in <module>
    from poster.streaminghttp import StreamingHTTPConnection, StreamingHTTPSConnection
ImportError: No module named poster.streaminghttp

**Comment by glides** [comment]
You're missing a dependency. To fix it all you need to do is install it.
However, if you followed the [wiki](https://github.com/n1nj4sec/pupy/wiki/Installation) you should already have it installed.
