### ISSUE TITLE
shell errors

### ISSUE THREAD

**Issue by User122333** [n1nj4sec/pupy#718]
Every command I try to run in the pupy shell results in a bunch of python errors, and a permission error. Does anyone know why this may be happening? Output I was getting (please note that Im on Linux Mint 19 tara, ran the installation WITH the compilation ["./create-workspace.py pupyws"], and am not running as root):

            _____                    _       _ _
 ___ ___   |  _  |_ _ ___ _ _    ___| |_ ___| | |   ___ ___
|___|___|  |   __| | | . | | |  |_ -|   | -_| | |  |___|___|
           |__|  |___|  _|_  |  |___|_|_|___|_|_|
                     |_| |___|

                   v1.8 (Aug 2018)

  
  Upstream: https://github.com/n1nj4sec/pupy
  
  The usage of this software to access any system,
  service, or network without the owner's consent is
  expressly forbidden.
  
  Please follow https://www.eccouncil.org/code-of-ethics/
  
  Good luck!
  
[*] IGDClient enabled
[*] WebServer started (0.0.0.0:9000, webroot=/BswoqOu8ik)
[-] Listen: ssl: 443: Insufficient privileges to bind
>> listen -l
[-] Traceback (most recent call last):
  File "/home/roi/pupy/pupy/pupylib/PupyCmd.py", line 429, in cmdloop
    cmd.Cmd.cmdloop(self, intro)
  File "/usr/lib/python2.7/cmd.py", line 143, in cmdloop
    stop = self.postcmd(stop, line)
  File "/home/roi/pupy/pupy/pupylib/PupyCmd.py", line 579, in postcmd
    readline.write_history_file('.pupy_history')
IOError: [Errno 13] Permission denied
>> >>

**Comment by alxchk** [comment]
```
Listen: ssl: 443: Insufficient privileges to bind
```

You need either select port > 1024 or use privileged account.

```
readline.write_history_file('.pupy_history')
IOError: [Errno 13] Permission denied
>> >>
```

For some strange reason you don't have access to create/write history file

**Comment by alxchk** [comment]
In case you are not familiar with linux/python it's better to follow the wiki.

**Comment by User122333** [comment]
I am following the wiki. Literally all I did was clone it, install dependencies, and followed the pupy installation guide on the wiki for Debian/Ubuntu.

**Comment by alxchk** [comment]
Well, there are several things why you get things like this.

`create-workspace.py` itself is wrapper around virtualenv. This thing creates environment with all dependencies at your *workspace*, **/home/roi/pupy/pupyws** in your case (`./create-workspace.py pupyws`). Script also put **pupysh** wrapper (which calls python with path to environment) somewhere to your's user local dir. When you use **sudo**, you don't have this for *root* user. Deps are missing, things goes wrong. I'm not sure, but maybe you have inital error was because you cloned repo as root.

I suggest to do next steps. If you don't need 443 port (you don't), don't run as root.

Create workspace somewhere at home directory, like **./create-workspace.sh /home/roi/pupy**.
Ensure your user can write there (well, I don't see how this may be otherwise).

Execute pupysh using wrapper script (i.e. **pupysh**, ensure it's in your PATH).
You will have this  `[-] Listen: ssl: 443: Insufficient privileges to bind` message.

After that execute:
```
config set listeners ssl 4782 
config save
restart
```
Section `[listeners]` has default args for listeners,  this will change port 443 to something else, bigger than 1024.

**Comment by User122333** [comment]
whenever I try to run create-workspace.py without root privilages I get this:

[+] Pupy at /home/user/pupy
[+] Compile common templates
/home/user/pupy

[+] Build sources with toolchain alxchk/tc-windows
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create?name=build-pupy-windows: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
Traceback (most recent call last):
  File "./create-workspace.py", line 196, in <module>
    main()
  File "./create-workspace.py", line 84, in main
    ], env=env, cwd=os.path.join(args.pupy_git_folder, 'client'))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/user/pupy/client/build-docker.sh']' returned non-zero exit status 126
sidenote, thanks for trying to help. will just get a kali vm or something

**Comment by alxchk** [comment]
Well, you need to add your user to docker group to be able to communicate with docker

**Comment by glides** [comment]
> "You need either select port > 1024 or use privileged account."

I know this is old, but I wanted to add a workaround for anyone googling and running across this issue.

Since pupy is generates it's own files (example: pupy_history) and payloads with the user that's running the process as the owner this isn't always a satisfactory solution for me as it's annoying to spread root owned files in my user directory (just a personal preference so I try to avoid it).

You can run pupy under your current user and bind to the lower ports by adding the python binary that is used to run pupy as a CAP_NET_BIND_SERVICE:

`sudo setcap CAP_NET_BIND_SERVICE=+eip ~/pupyws/bin/python2`

The path has to go to the binary, not the symlink. Cheers.
