### ISSUE TITLE
Debian 9 as host, Raspbian as client issues

### ISSUE THREAD

**Issue by gitxmax** [n1nj4sec/pupy#719]
Hello
Pupy script installed on Debian 9, with zero errors

py - as payload
ex.: pupygen.py -f py connect --host ip:port -t http

listener enabled on "port"
several transport methods tried, with the same error on client side:

WARNING:pupy.network.pss:Datagram based stream is not available: KCP missing
ERROR:pupy.network:Transport ec4 disabled: cannot import name EC4TransportServer
Traceback (most recent call last):
  File "/root/pupy/pupy/network/lib/__init__.py", line 44, in <module>
ImportError: cannot import name EC4TransportServer
ERROR:pupy.network:Transport ecm disabled: cannot import name ECMTransportServer
Traceback (most recent call last):
  File "/root/pupy/pupy/network/lib/__init__.py", line 51, in <module>
ImportError: cannot import name ECMTransportServer
ERROR:root:cannot import name DNSCncLauncher: DNSCncLauncher disabled
Traceback (most recent call last):
  File "network/conf.py", line 93, in <module>
ImportError: cannot import name DNSCncLauncher
ERROR:root:cannot import name DNSCncLauncher: DNSCncLauncher disabled
Traceback (most recent call last):
  File "network/conf.py", line 93, in <module>
ImportError: cannot import name DNSCncLauncher

Despite the error, the client get's connected to the host.
But, when I issue connect --host clientip command, the pupysh.py spits out:

>> connect --host ip
2018-12-16 01:23:17,866| timed out
Traceback (most recent call last):
  File "/root/pupy/pupy/network/lib/launchers/connect.py", line 87, in iterate
    s = client.connect(self.rhost, self.rport)
  File "/root/pupy/pupy/network/lib/clients.py", line 146, in connect
    return self.connect_pupy(host, port)
  File "/root/pupy/pupy/network/lib/clients.py", line 159, in connect_pupy
    socket = super(PupySSLClient, self).connect(host, port)
  File "/root/pupy/pupy/network/lib/clients.py", line 50, in connect
    s.connect(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out
[-] Traceback (most recent call last):
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 429, in cmdloop
    cmd.Cmd.cmdloop(self, intro)
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 220, in onecmd
    return self.default(line)
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 378, in default
    return self.execute(line)
  File "/root/pupy/pupy/pupylib/PupyCmd.py", line 394, in execute
    clients_filter)
  File "/root/pupy/pupy/commands/__init__.py", line 130, in execute
    command.do(server, handler, config, parsed_args)
  File "/root/pupy/pupy/commands/connect.py", line 14, in do
    server.connect_on_client(launcher)
  File "/root/pupy/pupy/pupylib/PupyServer.py", line 957, in connect_on_client
    stream=launcher.iterate().next()
StopIteration

 Seen similar issues here and pupy/pupy/external/pykcp/kcp is a suspect
But, in my case, the folder contains all the files.

**Comment by alxchk** [comment]
You get those errors because there are no libs like pycryptodome, psutil etc on the rasbian side.
You are missing dependencies. Likely at least Cryptodome. Rasbian means ARM? There is no prebuilt client for arm and no pupy toolchain for that. You should compile it by yourself there. If you are running `py` payload, then you can try to stay with ssl transport only (but honestly I didn't check will it work without prebuild bundles or not).

So. You should either build client for ARM, or install python deps there. Likely this will resolve issues.

**Comment by gitxmax** [comment]
Thanks
Installing some of the dependencies seemed to have helped, no errors so far

-e external/pykcp
rpyc==3.4.4
pycryptodome==3.7.0
psutil
rsa
netaddr
tinyec
poster
u-msgpack-python
dnslib

would be great to have a client compiled, but I'm not that strong at cross compiling...

**Comment by rayleeafar** [comment]
> > would be great to have a client compiled, but I'm not that strong at cross compiling...
> 
> It's very unlikely something exists for python. The only way to do it on x86 likely using qemu. But you can compile this on the target itself

Hi~ May I ask a question,  Do you have any suggestions on how to compile pupy client for ARM architecture, many thanks~∩_∩~
