### ISSUE TITLE
No module name elftools

### ISSUE THREAD

**Issue by JohnCodeK** [n1nj4sec/pupy#731]
I run pupygen.py and get this F*cking Error

`No handlers could be found for logger "pupy.network.pss"
Traceback (most recent call last):
  File "pupygen.py", line 31, in <module>
    from pupylib.utils.network import get_listener_ip, get_listener_port
  File "/home/ck/Penetrating/tools/pupy/pupy/pupylib/__init__.py", line 21, in <module>
    from PupyCmd import PupyCmdLoop
  File "/home/ck/Penetrating/tools/pupy/pupy/pupylib/PupyCmd.py", line 36, in <module>
    from .PupyModule import (
  File "/home/ck/Penetrating/tools/pupy/pupy/pupylib/PupyModule.py", line 18, in <module>
    from .PupyCompleter import PupyModCompleter, void_completer, list_completer
  File "/home/ck/Penetrating/tools/pupy/pupy/pupylib/PupyCompleter.py", line 24, in <module>
    from .payloads.dependencies import paths
  File "/home/ck/Penetrating/tools/pupy/pupy/pupylib/payloads/dependencies.py", line 10, in <module>
    from elftools.elf.elffile import ELFFile
ImportError: No module named elftools.elf.elffile
`

**Comment by Anonymous811822525** [comment]
have u fixed it yet ? i am running the same error too guess will have to fix it on our own ow wait for somebody to comment.

i am gonna contact the creator and do my research and ill tell you if ive fixed it.

**Comment by alxchk** [comment]
https://github.com/n1nj4sec/pupy/blob/unstable/pupy/requirements.txt#L39
