### ISSUE TITLE
The persistence script was not working?

### ISSUE THREAD

**Issue by ibaka9** [n1nj4sec/pupy#748]
[-] payload generation failed: pupwinutils.persistence
Traceback (most recent call last):
  File "/home/ubuntu/tools/pupy_new/pupy/pupy/commands/gen.py", line 133, in do
    output = pupygen.pupygen(args, config, server, handler.display)
  File "/home/ubuntu/tools/pupy_new/pupy/pupy/pupygen.py", line 591, in pupygen
    debug=args.debug_scriptlets)
  File "/home/ubuntu/tools/pupy_new/pupy/pupy/pupygen.py", line 485, in pack_scriptlets
    script_code = sp.pack()
  File "/home/ubuntu/tools/pupy_new/pupy/pupy/scriptlets/__init__.py", line 141, in pack
    dependencies.importer(requirements, os=self.os)
  File "/home/ubuntu/tools/pupy_new/pupy/pupy/pupylib/payloads/dependencies.py", line 201, in importer
    blob, modules, _ = package(dependencies, os, arch, posix=posix, native=native)
  File "/home/ubuntu/tools/pupy_new/pupy/pupy/pupylib/payloads/dependencies.py", line 602, in package
    native=native
  File "/home/ubuntu/tools/pupy_new/pupy/pupy/pupylib/payloads/dependencies.py", line 560, in _package
    raise NotFoundError(module_name)
NotFoundError: pupwinutils.persistence

This is the command i used.
`gen -f client -O windows -A x64 -s keylogger -s persistence`

**Comment by glides** [comment]
That scriptlet appears to be out of date.
Back in Nov persistence methods were updated to be managed winpwnage, but the script wasn't updated.

https://github.com/n1nj4sec/pupy/commit/8e223560ffb7ac707dd0d9d8e36a56b517ce202b

**Comment by brezuicabogdan** [comment]
Any updates to this?

**Comment by Vazza202** [comment]
@brezuicabogdan as far as I know you can use `gen -l` to list the persistence args but there's not much to run off of, as far as it shows. If you have any update on how to execute persistence, please reply back with some info on how you did it. I'm in the dark on this one.

**Comment by arschlochnop** [comment]
Fixed: https://github.com/n1nj4sec/pupy/pull/880
