### ISSUE TITLE
Pupy build from toolchain error

### ISSUE THREAD

**Issue by him4nsh** [n1nj4sec/pupy#767]
### Unable to compile the Pupy from the Docker Toolchain , getting the error as follows:-

ERROR: Command "/usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-EUoEsJ/pyuv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-W9dlbA/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-EUoEsJ/pyuv/
Traceback (most recent call last):
  File "create-workspace.py", line 196, in <module>
    main()
  File "create-workspace.py", line 84, in main
    ], env=env, cwd=os.path.join(args.pupy_git_folder, 'client'))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/<username>/pupy/client/build-docker.sh']' returned non-zero exit status 1

Please suggest the solutions for this ..

**Comment by wuppp** [comment]
I just change this line.
https://github.com/n1nj4sec/pupy/blob/4b78dc582526294141185c3c1c602cc00dc9c0b1/client/sources-linux/build-docker.sh#L69 
```
    CFLAGS="$CFLAGS -arch i386 -arch x86_64 -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DS_ISSOCK(m)='(((m) & S_IFMT) == S_IFSOCK)'" \
```

https://github.com/saghul/pyuv/issues/131#issuecomment-23895603

**Comment by alxchk** [comment]
You need to check output manually. Something went wrong with docker
