### ISSUE TITLE
Can't create a session - ERROR:pupy.network.launcher.connect:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

### ISSUE THREAD

**Issue by Hawax** [n1nj4sec/pupy#769]
**ERROR:pupy.network.launcher.connect:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
Traceback (most recent call last):
  File "network/lib/launchers/connect.py", line 74, in iterate
  File "network/lib/launchers/connect.py", line 98, in connect_to_host
  File "network/lib/clients.py", line 158, in connect
  File "network/lib/clients.py", line 208, in connect_pupy
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
^CTraceback (most recent call last):
  File "pupy_mPtF1m.py", line 4, in <module>**

What can I do with this?

**Comment by alxchk** [comment]
Likly certs were expired

**Comment by joker8989** [comment]
If the certs were expired what's that mean? you lose all your clients? have not played with this project...
waiting for it :)

**Comment by joker8989** [comment]
can someone answer my question above? if my cert were expired for some reason all my for example 20 clients will be lost right?

**Comment by alxchk** [comment]
Sure. Default ssl cert generated for one year.
