### ISSUE TITLE
No handlers could be found for logger "pupy.network.pss"

### ISSUE THREAD

**Issue by TarushS** [n1nj4sec/pupy#772]
root@kali:~/pupy/pupy# ./pupygen.py -f apk -o hax.apk connect --host anonimbus.ddns.net:8080
No handlers could be found for logger "pupy.network.pss"
usage: pupygen.py [-h]
                  [-f {client,py,pyinst,py_oneliner,ps1,ps1_oneliner,rubber_ducky,csharp,.NET,.NET_oneliner}]
                  [-O {android,windows,linux,solaris}] [-A {x86,x64}] [-U]
                  [-P PACKER] [-S] [-o OUTPUT]
                  [-d <ATTEMPTS> <MIN SEC> <MAX SEC>] [-D OUTPUT_DIR]
                  [-s SCRIPTLET] [-l] [-E] [--no-use-proxy]
                  [--oneliner-nothidden] [--debug-scriptlets] [--debug]
                  [--workdir WORKDIR]
                  [{bind,auto_proxy,dnscnc,connect}] ...
pupygen.py: error: argument -f/--format: invalid choice: 'apk' (choose from 'client', 'py', 'pyinst', 'py_oneliner', 'ps1', 'ps1_oneliner', 'rubber_ducky', 'csharp', '.NET', '.NET_oneliner')

adnroid or windows isnt in the list to choose from

**Comment by TarushS** [comment]
{UPDATE}
after trying ./install.sh

root@kali:~/pupy/pupy# ./pupygen.py
No handlers could be found for logger "pupy.network.pss"
WARNING:root:No module named ntlm: socks module disabled, auto_connect unavailable
Traceback (most recent call last):
  File "./pupygen.py", line 31, in <module>
    from pupylib.utils.network import get_listener_ip, get_listener_port
  File "/root/pupy/pupy/pupylib/__init__.py", line 27, in <module>
    from PupyServer import PupyServer
  File "/root/pupy/pupy/pupylib/PupyServer.py", line 45, in <module>
    from pupylib.PupyOffload import PupyOffloadManager, OffloadProxyCommonError
  File "/root/pupy/pupy/pupylib/PupyOffload.py", line 13, in <module>
    from network.lib import socks
  File "/root/pupy/pupy/network/lib/socks.py", line 74, in <module>
    from ntlm import ntlm
ImportError: No module named ntlm
