### ISSUE TITLE
Package issues on system with selinux enabled

### ISSUE THREAD

**Issue by blark** [n1nj4sec/pupy#778]
I am not sure if this is related to SELinux or not, but I'm having issues with modules not working/loading. 

Here is an example: 

```
>> load_package scandir
[+] package loaded
>> ls
[!] Load scandir failed: Exception: '_scandir'
[!] Error loading package scandir (scandir.pyo pkg=False) : '_scandir' Traceback (most recent call last):
  File "pupyimporter", line 570, in load_module
  File "pupyimporter", line 61, in loadpy
  File "scandir.py", line 30, in <module>
  File "pupyimporter", line 626, in load_module
KeyError: '_scandir'
[!] Load pupyutils.basic_cmds failed: Exception: '_scandir'
[!] Error loading package pupyutils.basic_cmds (pupyutils/basic_cmds.pyo pkg=False) : '_scandir' Traceback (most recent call last):
  File "pupyimporter", line 570, in load_module
  File "pupyimporter", line 61, in loadpy
  File "pupyutils/basic_cmds.py", line 16, in <module>
  File "pupyimporter", line 570, in load_module
  File "pupyimporter", line 61, in loadpy
  File "scandir.py", line 30, in <module>
  File "pupyimporter", line 626, in load_module
KeyError: '_scandir'
[-] _scandir
```

This is a python payload, and the `ls` command works on other systems... any advice or feedback you could provide would be appreciated!

Thanks

**Comment by alxchk** [comment]
SELinux may prohibit to do mmap/mprotect with executable flag. In this case all .so loads become impossible. Pupy heavily use dynamic libraries. Functionality from restricted context in SELinux-enabled system is very limited (well,  almost unusable)

**Comment by blark** [comment]
Is there an easy way to check if this is the problem? I can do some testing/debugging to check... Thanks

**Comment by alxchk** [comment]
Simplest way is to strace process. If there will be -1 EACCESS (or something like that) on mmap/mprotect calls, then it's selinux. You are using pure python payload, aren't you?

**Comment by blark** [comment]
Yes, I am using a Python payload. 

For testing purposes I fired up a CentOS VPS **without** SELinux and it's exhibiting similar problems, although not as many things are broken. For example, now `ls` works fine but `w` and `last` commands cause an exception.  (note: When I use a binary payload everything seems to work fine.)

Here is the error output from `w`:
```
>> w
[!] Load psutil failed: Exception: cannot import name _common
[!] Error loading package psutil (psutil/__init__.pyo pkg=True) : cannot import name _common Traceback (most recent call last):
  File "pupyimporter", line 570, in load_module
  File "pupyimporter", line 61, in loadpy
  File "site-packages/psutil/__init__.py", line 41, in <module>
ImportError: cannot import name _common
[!] Load pupyps failed: Exception: cannot import name _common
[!] Error loading package pupyps (pupyps.pyo pkg=False) : cannot import name _common Traceback (most recent call last):
  File "pupyimporter", line 570, in load_module
  File "pupyimporter", line 61, in loadpy
  File "pupyps.py", line 3, in <module>
  File "pupyimporter", line 570, in load_module
  File "pupyimporter", line 61, in loadpy
  File "site-packages/psutil/__init__.py", line 41, in <module>
ImportError: cannot import name _common
2019-07-08 17:58:10,092| cannot import name _common

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "rpyc/core/protocol.py", line 347, in _dispatch_request
  File "rpyc/core/protocol.py", line 630, in _handle_getattr
  File "rpyc/core/protocol.py", line 596, in _access_attr
  File "rpyc/core/service.py", line 118, in __getattr__
  File "rpyc/core/service.py", line 115, in __getitem__
  File "", line 667, in exposed_getmodule
  File "pupyimporter", line 570, in load_module
  File "pupyimporter", line 61, in loadpy
  File "pupyps.py", line 3, in <module>
  File "pupyimporter", line 570, in load_module
  File "pupyimporter", line 61, in loadpy
  File "site-packages/psutil/__init__.py", line 41, in <module>
ImportError: cannot import name _common
Traceback (most recent call last):
  File "/home/ubuntu/pupy/pupy/modules/w.py", line 26, in run
    users = self.client.remote('pupyps', 'users')
  File "/home/ubuntu/pupy/pupy/pupylib/PupyClient.py", line 234, in remote
    remote_module = getattr(self.conn.modules, module)
  File "/home/ubuntu/pupy/ws/local/lib/python2.7/site-packages/rpyc/core/netref.py", line 151, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/home/ubuntu/pupy/ws/local/lib/python2.7/site-packages/rpyc/core/netref.py", line 72, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/home/ubuntu/pupy/pupy/network/lib/connection.py", line 387, in sync_request
    raise obj
ImportError: cannot import name _common

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "rpyc/core/protocol.py", line 347, in _dispatch_request
  File "rpyc/core/protocol.py", line 630, in _handle_getattr
  File "rpyc/core/protocol.py", line 596, in _access_attr
  File "rpyc/core/service.py", line 118, in __getattr__
  File "rpyc/core/service.py", line 115, in __getitem__
  File "", line 667, in exposed_getmodule
  File "pupyimporter", line 570, in load_module
  File "pupyimporter", line 61, in loadpy
  File "pupyps.py", line 3, in <module>
  File "pupyimporter", line 570, in load_module
  File "pupyimporter", line 61, in loadpy
  File "site-packages/psutil/__init__.py", line 41, in <module>
ImportError: cannot import name _common
```

**Comment by blark** [comment]
To add more context, I did `strace` on the CentOS vps when trying the `w` shortcut and the only error I see is (repeated a few times with different addresses):

```
read(3, 0x233e0d3, 2333)                = -1 EAGAIN (Resource temporarily unavailable)
```

**Comment by alxchk** [comment]
I will try to reproduce myself

**Comment by alxchk** [comment]
Can you restart the payload, and execute `ls` as first command?

**Comment by blark** [comment]
Tested, running `ls` first works fine but then subsequent commands such as `w` or `forward` produce the same exceptions as before. Thanks so much for your help on this! 

I did notice that the binary client works fine.
