### ISSUE TITLE
No module named basic_cmds for Android

### ISSUE THREAD

**Issue by kjoon41** [n1nj4sec/pupy#804]
I had a connect successfully with android phone but If I trying type 'ls' or 'cd' for see the list system files  then happend belows Error. how to finding the pupyutils/basic_cmds.pyo pkg?
please help. thanks

>> ls
[!] Load pupyutils.basic_cmds failed: Exception: undefined symbol: opendir
[!] Error loading package pupyutils.basic_cmds (pupyutils/basic_cmds.pyo pkg=False) : undefined symbol: opendir Traceback (most recent call last):
  File "pupyimporter", line 570, in load_module
  File "pupyimporter", line 61, in loadpy
  File "pupyutils/basic_cmds.py", line 16, in <module>
  File "/build/buildozer/android/platform/build/dists/pupy/private/lib/python2.7/site-packages/scandir.py", line 453, in <module>
  File "/build/buildozer/android/platform/build/build/other_builds/python2-openssl/armeabi-v7a/python2/python-install/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
  File "/build/buildozer/android/platform/build/build/other_builds/python2-openssl/armeabi-v7a/python2/python-install/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
AttributeError: undefined symbol: opendir
[-] No module named basic_cmds

**Comment by kjoon41** [comment]
This happened problems at low android version 4.4.  this is a not problems at android version 8.0 when i tried. Thanks,
