### ISSUE TITLE
Offset to edit the config have not been found

### ISSUE THREAD

**Issue by partlyconfig** [n1nj4sec/pupy#828]
Just made a fresh install and receiving several offset errors in pupysh though I haven't moved any of the config am I missing something?

gen -f client -O windows -A x64 bind --port 12345 -t http
and
gen -f client -O windows -A x64 connect --host 192.168.1.5:12345 -t http

`Traceback (most recent call last):
  File "pupy/pupy/commands/gen.py", line 133, in do
    output = pupygen.pupygen(args, config, server, handler.display)
  File "pupy/pupy/pupygen.py", line 663, in pupygen
    compressed=not (args.uncompressed or args.packer)
  File "/pupy/pupy/pupygen.py", line 447, in generate_binary_from_template
    return generator(display, template, config, compressed, debug), filename, makex
  File "pupy/pupy/pupygen.py", line 72, in get_edit_binary
    raise Exception("Error: the offset to edit the config have not been found")
Exception: Error: the offset to edit the config have not been found`

**Comment by alxchk** [comment]
By default images are downloaded from my repo, which was desynchronized with this one. Maybe that was the issue.
