### ISSUE TITLE
Exception in thread Authentication Thread 

### ISSUE THREAD

**Issue by oooaoaSH** [n1nj4sec/pupy#830]
Exception in thread Authentication Thread (::ffff:127.0.0.1:52676):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/pupy/network/lib/servers.py", line 122, in _setup_connection
    wrapper, credentials = self.authenticator(sock)
  File "/usr/share/pupy/network/transports/ssl/conf.py", line 54, in __call__
    ciphers=self.ciphers
  File "/usr/lib/python2.7/ssl.py", line 931, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 599, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:727)

**Comment by minahil98** [comment]
have you found a solution? i'm having the same issue:-
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pupy/pupy/pupy/network/lib/servers.py", line 113, in _setup_connection
    wrapper, credentials = self.authenticator(sock)
  File "/home/pupy/pupy/pupy/network/transports/ssl/conf.py", line 55, in __call__
    ciphers=self.ciphers
  File "/usr/lib/python2.7/ssl.py", line 933, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590)

**Comment by jayrod** [comment]
Exception in thread Authentication Thread (127.0.0.1:44090):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/pupy/pupy/network/lib/servers.py", line 113, in _setup_connection
    wrapper, credentials = self.authenticator(sock)
  File "/opt/pupy/pupy/network/transports/ssl/conf.py", line 58, in __call__
    ciphers=self.ciphers
  File "/usr/lib/python2.7/ssl.py", line 931, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 599, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error

Same issue still hapenning on version 1.8 of pupyshell.

**Comment by reecep55** [comment]
Having the same issue:

SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:727)

Exception in thread Authentication Thread (192.168.116.136:49773):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/pupy/network/lib/servers.py", line 122, in _setup_connection
    wrapper, credentials = self.authenticator(sock)
  File "/pupy/network/transports/ssl/conf.py", line 54, in __call__
    ciphers=self.ciphers
  File "/usr/lib/python2.7/ssl.py", line 931, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 599, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:727)
