### ISSUE TITLE
from tinyec.ec import ( ImportError: cannot import name to_bytes

### ISSUE THREAD

**Issue by isa84sfs** [n1nj4sec/pupy#841]
root@kali:~/attack/tools/pupy/pupy# ./pupygen.py
No handlers could be found for logger "pupy.network"
Traceback (most recent call last):
  File "./pupygen.py", line 33, in <module>
    from pupylib.utils.listener import get_listener_ip, get_listener_port
  File "/root/attack/tools/pupy/pupy/pupylib/__init__.py", line 23, in <module>
    from PupyCredentials import Credentials
  File "/root/attack/tools/pupy/pupy/pupylib/PupyCredentials.py", line 18, in <module>
    from network.lib.transports.cryptoutils import ECPV
  File "/root/attack/tools/pupy/pupy/network/lib/transports/cryptoutils/__init__.py", line 43, in <module>
    from .ecpv import ECPV
  File "/root/attack/tools/pupy/pupy/network/lib/transports/cryptoutils/ecpv.py", line 11, in <module>
    **from tinyec.ec import (
ImportError: cannot import name to_bytes**

**Comment by xView60** [comment]
Someone found a fix?

**Comment by w-devin** [comment]
https://github.com/alexmgr/tinyec

tinyec, no to_bytes, from_bytes, ec2osp, osp2ec in tinyec/ec.py

emmmmmmmmm?

**Comment by alxchk** [comment]
https://github.com/alxchk/tinyec/

**Comment by w-devin** [comment]
> https://github.com/alxchk/tinyec/

thanks

**Comment by rfbasso** [comment]
I have tried uninstall and install again tinyec, and don't work... any ideas?

**Comment by w-devin** [comment]
> I have tried uninstall and install again tinyec, and don't work... any ideas?

the tinyec in this rep is https://github.com/alxchk/tinyec/, not the version installed by pip
