### ISSUE TITLE
Debian 10(Buster) install pupyws issue 

### ISSUE THREAD

**Issue by ihateadmins** [n1nj4sec/pupy#843]
i followed the installation guide and the command "./create-workspace.py pupyws" failed with "Likely you must to enable vsyscall=emulate"
But it does seem to be enabled on the system.
cat /usr/src/linux-headers-$(uname -r)/.config | grep VSYSCALL
```
CONFIG_GENERIC_TIME_VSYSCALL=y
CONFIG_X86_VSYSCALL_EMULATION=y
CONFIG_LEGACY_VSYSCALL_NONE=y
```
```
[+] Build complete
[+] Build linux64 using build-pupy-linux64-7795 (create)
Unable to find image 'alxchk/tc-linux64:latest' locally
latest: Pulling from alxchk/tc-linux64
90ad55894af3: Pull complete
214f438ad66f: Pull complete
Digest: sha256:ffd300ee4e3a532d74983854aa83b41a5f8de486d8af628664a7574bb8526e55
Status: Downloaded newer image for alxchk/tc-linux64:latest
[!] Likely you must to enable vsyscall=emulate
Traceback (most recent call last):
  File "./create-workspace.py", line 657, in <module>
    main()
  File "./create-workspace.py", line 563, in main
    templates, args.image_tag, args.persistent
  File "./create-workspace.py", line 256, in build_templates
    subprocess.check_call(args, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'docker', u'run', u'--rm', u'--name=build-pupy-linux64-7795', u'--ulimit', u'nofile=65535:65535', u'--security-opt', u'label=disable', u'--mount', u'type=bind,src=/root/Downloads/pupy/pupy,target=/build/workspace/project', u'alxchk/tc-linux64:latest', u'client/sources-linux/build-docker.sh']' returned non-zero exit status 139
```
OS: Debian GNU/Linux 10 (buster) x86_64
Kernel: 4.19.0-9-amd64

(bash)log https://pastebin.com/fF7QBv68

Thanks in advance

**Comment by alxchk** [comment]
You have support, but it doesn't mean it's enabled.

grep vsyscall /proc/self/maps

**Comment by koushui** [comment]
> grep vsyscall /proc/self/maps

plz how to set up enable vsyscall= Emulate???

**Comment by koushui** [comment]
I find method Set enable  vsyscall= Emulate
1、Modify the kernel parameters: at /etc/default/grub add vsyscall=emulate to GRUB_CMDLINE_LINUX_DEFAULT (if for some reason you want it at recovery mode, then GRUB_CMDLINE_LINUX as well)
2、Run update-grub   （It's important. I just lost this step）
3、Reboot.

BTW，Pupy was really poorly documented and had problems during deployment

**Comment by koushui** [comment]
I still get the same error even though I have enable vsyscall= Emulate , why is that?


Step 10/13 : ADD        https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20200229/mimikatz_trunk.zip   /                                                                                                                       opt/mimikatz
ADD failed: failed to GET https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20200229/mimikatz_trunk.zip w                                                                                                                       ith status 404 Not Found: Not Found
Traceback (most recent call last):
  File "create-workspace.py", line 657, in <module>
    main()
  File "create-workspace.py", line 575, in main
    args.network, templates, args.squash
  File "create-workspace.py", line 401, in create_container_env
    subprocess.check_call(build_command, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', u'build', u'-t', u'pupy-python2-env', u'-f', u'/root/pupy/pupy/conf                                                                                                                       /Dockerfile.env', u'/root/pupy/pupy']' returned non-zero exit status 1
root@server:~/pupy#
root@server:~/pupy# grep vsyscall /proc/self/maps
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
root@server:~/pupy# cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-4.19.0-9-cloud-amd64 root=UUID=d609a734-b8b7-48a7-b7fb-3b65068ff83c ro console=tty0 console=ttyS0,115200 earlyprintk=ttyS0,115200 elevator=noop scsi_mod.use_blk_mq=Y quiet vsyscall=emulate

**Comment by koushui** [comment]
Previous error, need to edit file to fix /pupy/pupy/conf/Dockerfile.env Download address for mimikatz_trunk.zip
