### ISSUE TITLE
how to get back clients when creds expire after a year?

### ISSUE THREAD

**Issue by minahil98** [n1nj4sec/pupy#847]
is there anyway to disable certificate checks when the certs expire after a year?
or the clients are lost forever after a year? any workaround will be appreciated.

My creds have expired and i'm getting the following error:-
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pupy/pupy/pupy/network/lib/servers.py", line 113, in _setup_connection
    wrapper, credentials = self.authenticator(sock)
  File "/home/pupy/pupy/pupy/network/transports/ssl/conf.py", line 55, in __call__
    ciphers=self.ciphers
  File "/usr/lib/python2.7/ssl.py", line 933, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590)

**Comment by alxchk** [comment]
Certs are checked from both sides, so unlikely.
You can try to comment out the validation part, but this shouldnt help for the clients, which you dont have access to.
Don't use ssl for long term things.

**Comment by s1st3r** [comment]
Expand SSL time on code, on how long you wonna have access to.
