### ISSUE TITLE
tlsv1 alert unknown ca (_ssl.c:727)

### ISSUE THREAD

**Issue by njucw** [n1nj4sec/pupy#848]
Hi, Pupy team, 
when i try to test pupy on win7 x64,  ```pupysh.py``` shows this error :
```bash
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/john/Desktop/pupy/pupy/network/lib/servers.py", line 122, in _setup_connection
    wrapper, credentials = self.authenticator(sock)
  File "/home/john/Desktop/pupy/pupy/network/transports/ssl/conf.py", line 54, in __call__
    ciphers=self.ciphers
  File "/usr/lib/python2.7/ssl.py", line 931, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 599, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:727)
```
i check ```pupy/pupylib/PupyCredentials.py ```and find nothing wrong, 
then i delete  ```root/.config/pupy/crypto/credentials.py``` to complie again and still get this error.
seem like i got wrong certificates but i can't fix it. please help.
my pupy server OS is Kali 2020.2 and i use docker to build it, thx!

**Comment by njucw** [comment]
Found reason:
use ```pupysh.py``` to generate client instead of ```pupygen.py```. 
Total different certs used.
