### ISSUE TITLE
Debian GNU/Linux 10 run ./create-workspace.py pupyws display AttributeError: 'module ' object has no attribute 'create_environment'

### ISSUE THREAD

**Issue by koushui** [n1nj4sec/pupy#850]
root@test-server:~/pupy# uname -a
Linux test-serve4.19.0-9-cloud-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
root@test-serve:~/pupy# cat /etc/issue
Debian GNU/Linux 10 \n \l

root@test-server:~/pupy#./create-workspace.py pupyws
[+] Create workdir
Traceback (most recent call last):
  File "./create-workspace.py", line 657, in <module>
    main()
  File "./create-workspace.py", line 582, in main
    workdir, git_folder, 'docker', templates
  File "./create-workspace.py", line 322, in create_virtualenv
    virtualenv.create_environment(workdir)
AttributeError: 'module' object has no attribute 'create_environment'
 
How do you solve this problem?

**Comment by alxchk** [comment]
This is because of virtualenv update. But it should be fixed in current HEAD. Are use using up to date repo?
