### ISSUE TITLE
Docker environment run pupysh error：Datagram based stream is not available: KCP missing

### ISSUE THREAD

**Issue by koushui** [n1nj4sec/pupy#851]
root@test-server:~# pupysh                                                       \
2020-06-17 18:04:27,809| Datagram based stream is not available: KCP missing

>> listen -a kc4 1234                                            
2020-06-17 18:09:49,978| No module named kcp                     
Traceback (most recent call last):                               
  File "/pupy/pupylib/PupyServer.py", line 1070, in add_listener 
    self.listeners[name].init()                                  
  File "/pupy/pupylib/PupyServer.py", line 277, in init          
    external_port=external_port                                  
  File "/pupy/network/lib/servers.py", line 216, in __init__     
    self.kcp = __import__('kcp')                                 
ImportError: No module named kcp                                 
[-] kc4: 1921: No module named kcp    

root@test-server:~#~/pupy/pupy/conf# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED		STATUS              PORTS               NAMES
277d1e5f01db        pupy-python2-env    "python -OB /pupy/pu…"   3 hours ago	Up 2 hours                              pupy-dcae

  
root@test-server:~#~/pupy/pupy/conf# docker images
REPOSITORY              TAG                 IMAGE ID            CREATED			SIZE
pupy-python2-env        latest              b835ff051a2a        10 days ago		615MB
debian                  buster-slim         108d75da320f        4 weeks ago		69.2MB
alxchk/tc-android       latest              df74c7fbe0c1        2 months ago	3.8GB
alxchk/tc-linux32       latest              40f1323a6f27        2 months ago	416MB
alxchk/tc-windows       latest              8f2e56695b98        2 months ago	4.25GB
alxchk/tc-linux64       latest              b816f5561b29        2 months ago	543MB
alxchk/pupy             base-unstable       75732e2294f4        3 months ago	552MB
alxchk/tc-linux-armhf   latest              34b3bc98237e        5 months ago	431MB

Then i tried executing the following command to solve the problem:
root@test-server:docker exec -i -t pupy-dcae /bin/bash
root@pupy:/#cd pupy
root@pupy:/#pip install -e external/pykcp

Hopefully the next release of docker will fix this problem. btw, the current wiki is too simple and Outdated, in the actual deployment process, whether it is docker or direct installation, there are a variety of problems, can you improve the FAQ for various questions on the wiki ?

**Comment by alxchk** [comment]
Can you check the content of the folder at the git-root://pupy/external/pykcp/kcp ?

**Comment by koushui** [comment]
First I run "pip install -e external/pykcp" in the host directory, then I run "/pupyws/bin/pupysh-update" in the host, but not solve problem,and finally run "pip install -e external/pykcp" in the docker, so now I'm not sure if pip/external/pykcp/kcp is the original content of the directory.
The directory I am checking is as follows.

root@testserver:~/pupy/pupy/external/pykcp# ls -al kcp
total 128
drwxr-xr-x 2 root root  4096 Jun 15 06:32 .
drwxr-xr-x 5 root root  4096 Jun 17 18:16 ..
-rw-r--r-- 1 root root    65 Jun 15 06:32 .git
-rw-r--r-- 1 root root   106 Jun 15 06:32 .travis.yml
-rw-r--r-- 1 root root  1090 Jun 15 06:32 LICENSE
-rw-r--r-- 1 root root 13380 Jun 15 06:32 README.en.md
-rw-r--r-- 1 root root 15228 Jun 15 06:32 README.md
-rw-r--r-- 1 root root  5362 Jun 15 06:32 donation.png
-rw-r--r-- 1 root root 32112 Jun 15 06:32 ikcp.c
-rw-r--r-- 1 root root 12202 Jun 15 06:32 ikcp.h
-rw-r--r-- 1 root root   735 Jun 15 06:32 kcp.svg
-rw-r--r-- 1 root root  2114 Jun 15 06:32 protocol.txt
-rw-r--r-- 1 root root  4703 Jun 15 06:32 test.cpp
-rw-r--r-- 1 root root  5298 Jun 15 06:32 test.h
root@testserver:~/pupy/pupy/external/pykcp# ls -al
total 284
drwxr-xr-x  5 root root   4096 Jun 17 18:16 .
drwxr-xr-x 16 root root   4096 Jun 15 06:31 ..
-rw-r--r--  1 root root     50 Jun 15 06:32 .git
-rw-r--r--  1 root root     32 Jun 15 06:32 .gitignore
-rw-r--r--  1 root root     76 Jun 15 06:32 .gitmodules
drwxr-xr-x  2 root root   4096 Jun 17 18:16 KCP.egg-info
drwxr-xr-x  4 root root   4096 Jun 17 18:13 build
-rw-r--r--  1 root root   1312 Jun 15 06:32 clock.c
drwxr-xr-x  2 root root   4096 Jun 15 06:32 kcp
-rwxr-xr-x  1 root root 206760 Jun 17 18:13 kcp.so
-rw-r--r--  1 root root   5364 Jun 15 06:32 plibc_inet_ntop.c
-rw-r--r--  1 root root  32119 Jun 15 06:32 pykcp.c
-rw-r--r--  1 root root    513 Jun 15 06:32 setup.py
root@testserver:~/pupy/pupy/external/pykcp# stat pykcp.c
  File: pykcp.c
  Size: 32119           Blocks: 64         IO Block: 4096   regular file
Device: 801h/2049d      Inode: 417854      Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-06-17 17:39:25.656000000 +0000
Modify: 2020-06-15 06:32:29.204000000 +0000
Change: 2020-06-15 06:32:29.204000000 +0000
 Birth: -
root@testserver:~/pupy/pupy/external/pykcp# stat kcp
  File: kcp
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 801h/2049d      Inode: 417852      Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-06-17 17:36:46.516000000 +0000
Modify: 2020-06-15 06:32:31.588000000 +0000
Change: 2020-06-15 06:32:31.588000000 +0000
 Birth: -
root@testserver:~/pupy/pupy/external/pykcp# stat kcp/ikcp.c
  File: kcp/ikcp.c
  Size: 32112           Blocks: 64         IO Block: 4096   regular file
Device: 801h/2049d      Inode: 417862      Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-06-17 17:39:26.296000000 +0000
Modify: 2020-06-15 06:32:31.588000000 +0000
Change: 2020-06-15 06:32:31.588000000 +0000
 Birth: -
root@testserver:~/pupy/pupy/external/pykcp# stat kcp.so
  File: kcp.so
  Size: 206760          Blocks: 408        IO Block: 4096   regular file
Device: 801h/2049d      Inode: 393643      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-06-17 18:17:13.592000000 +0000
Modify: 2020-06-17 18:13:37.000000000 +0000
Change: 2020-06-17 18:16:47.532000000 +0000
 Birth: -
root@testserver:~/pupy/pupy/external/pykcp#

**Comment by muhammeteminturgut** [comment]
Same issue here. Please update current wiki.
