### ISSUE TITLE
make: *** [Makefile:145: resources/win32/library.zip] Error 1

### ISSUE THREAD

**Issue by koushui** [n1nj4sec/pupy#853]
When I run pupy_update.sh or  create-workspace.py， The script reports an error when executing “docker start -a build-pupy-windows-2d1b” command, how do I fix it?

USING MSVC pragmas, const_seg: .xzdata
THIS: Z:\build\workspace\project\client\build_library_zip.py
ROOT:  Z:\build\workspace\project
make: *** [Makefile:145: resources/win32/library.zip] Error 1

It actually tells me I'm missing the mcs package when I generate the file with gen -f .NET.Then when I run pupy-update.sh, I find that all my templates are not working anymore. How do I fix it when dave docker is missing packages? 

Also, when is a new wiki coming out, there are so many questions!

**Comment by alxchk** [comment]
> `make: *** [Makefile:145: resources/win32/library.zip] Error 1`

Try to pull repo. I enabled more verbose output from pupy loader in build_library_zip.py
Maybe it will be a bit more clearer what is wrong there. Also It may be required to recreate containers

> Also, when is a new wiki coming out, there are so many questions!
Oh.. Well.. Really do not have so many time for that

**Comment by koushui** [comment]
I Try to pull repo ，and then re-designate the pupyws directory by running the command ". /create-workspace.py -P pupyws".
There have been no errors "make: *** [Makefile:145: resources/win32/library.zip] Error 1".
The only errors were.：

`"ERROR: flake8-per-file-ignores 0.8.1 has requirement flake8<3.7,>=3, but you'll have flake8 3.8.3 which is incompatible.".**`

Is it possible to ignore the error, or comment out the file “requirements.txt” with " flake8-per-file-ignore"？？

Also, when I run the command ". /create-workspace.py -C 'linux32,linux64, windows,android,linux-armhf' -P pupyws", script Report the following errors：

`# Android packaging done!
# APK Wi-Fi-0.1-release-unsigned.apk available in the bin directory
[+] Build linux-armhf using build-pupy-linux-armhf-2d1b (existing)
ERRO[0000] error waiting for container: context canceled
Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"client/sources-linux/build-docker.sh\": stat client/sources-linux/build-docker.sh: no such file or directory": unknown
Traceback (most recent call last):
  File "./create-workspace.py", line 653, in <module>
    main()
  File "./create-workspace.py", line 559, in main
    templates, args.image_tag, args.persistent
  File "./create-workspace.py", line 270, in build_templates
    ], stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'docker', u'start', u'-a', u'build-pupy-linux-armhf-2d1b']' returned non-zero exit status 1

root@testserver:~/pupy# stat client/sources-linux/build-docker.sh
  File: client/sources-linux/build-docker.sh
  Size: 5344            Blocks: 16         IO Block: 4096   regular file
Device: 801h/2049d      Inode: 411379      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-06-27 17:35:26.172000000 +0000
Modify: 2020-06-27 17:35:26.144000000 +0000
Change: 2020-06-27 17:35:26.144000000 +0000
 Birth: -`

**Comment by alxchk** [comment]
There is no prebuild toolchain for arm. It's possible to build it manually (well, maybe some fixes needed). Its not ok for travis, because full emulation requires too many time.
