### ISSUE TITLE
Windows client binary doesn't work

### ISSUE THREAD

**Issue by Avatat** [n1nj4sec/pupy#855]
Hello,
I tried to build Windows binaries on Ubuntu 20.04 + Python 2.7 + Docker, using this commands:
```
pupy/client$ ./build-docker.sh
```
and
```
gen -f client -O windows -A x64 --debug connect --host 10.0.0.1:8443
```

A compiled binary doesn't work under Windows 7 and Windows 10:

<details>
  <summary>Click to show log</summary>

```
DEBUG:pupy:[L] backports.configparser.helpers remove backports/configparser/helpers.pyo from bundle / count = 585
DEBUG:pupy:loading module backports.configparser.helpers (ext: pyo)
DEBUG:pupy:Load backports.configparser.helpers from marshalled file (pyo)
DEBUG:pupy:Find module: pathlib/None/False
DEBUG:pupy:pathlib not found in []: not in 0 files
DEBUG:pupy:Find module: pupy.traceback/None/False
DEBUG:pupy:pupy.traceback not found in []: not in 0 files
DEBUG:pupy:Load importlib_metadata failed: Exception: No package metadata was found for importlib_metadata
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:13d", line 623, in <module>
  File "f:13d", line 585, in version
  File "f:13d", line 558, in distribution
  File "f:13d", line 215, in from_name
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Error loading package importlib_metadata (importlib_metadata/__init__.pyo pkg=True)
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:13d", line 623, in <module>
  File "f:13d", line 585, in version
  File "f:13d", line 558, in distribution
  File "f:13d", line 215, in from_name
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Load importlib_resources._compat failed: Exception: No package metadata was found for importlib_metadata
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:142", line 42, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:13d", line 623, in <module>
  File "f:13d", line 585, in version
  File "f:13d", line 558, in distribution
  File "f:13d", line 215, in from_name
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Error loading package importlib_resources._compat (importlib_resources/_compat.pyo pkg=False)
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:142", line 42, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:13d", line 623, in <module>
  File "f:13d", line 585, in version
  File "f:13d", line 558, in distribution
  File "f:13d", line 215, in from_name
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Load importlib_resources failed: Exception: No package metadata was found for importlib_metadata
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:147", line 5, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:142", line 42, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:13d", line 623, in <module>
  File "f:13d", line 585, in version
  File "f:13d", line 558, in distribution
  File "f:13d", line 215, in from_name
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Error loading package importlib_resources (importlib_resources/__init__.pyo pkg=True)
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:147", line 5, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:142", line 42, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:13d", line 623, in <module>
  File "f:13d", line 585, in version
  File "f:13d", line 558, in distribution
  File "f:13d", line 215, in from_name
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Load netaddr.compat failed: Exception: No package metadata was found for importlib_metadata
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:156", line 119, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:147", line 5, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:142", line 42, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:13d", line 623, in <module>
  File "f:13d", line 585, in version
  File "f:13d", line 558, in distribution
  File "f:13d", line 215, in from_name
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Error loading package netaddr.compat (netaddr/compat.pyo pkg=False)
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:156", line 119, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:147", line 5, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:142", line 42, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:13d", line 623, in <module>
  File "f:13d", line 585, in version
  File "f:13d", line 558, in distribution
  File "f:13d", line 215, in from_name
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Load netaddr.core failed: Exception: No package metadata was found for importlib_metadata
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:157", line 11, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:156", line 119, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:147", line 5, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:142", line 42, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:13d", line 623, in <module>
  File "f:13d", line 585, in version
  File "f:13d", line 558, in distribution
  File "f:13d", line 215, in from_name
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Error loading package netaddr.core (netaddr/core.pyo pkg=False)
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:157", line 11, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:156", line 119, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:147", line 5, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:142", line 42, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:13d", line 623, in <module>
  File "f:13d", line 585, in version
  File "f:13d", line 558, in distribution
  File "f:13d", line 215, in from_name
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Load netaddr failed: Exception: No package metadata was found for importlib_metadata
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:15a", line 18, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:157", line 11, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:156", line 119, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:147", line 5, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:142", line 42, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:13d", line 623, in <module>
  File "f:13d", line 585, in version
  File "f:13d", line 558, in distribution
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Error loading package netaddr (netaddr/__init__.pyo pkg=True)
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:15a", line 18, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:157", line 11, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:156", line 119, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:147", line 5, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:142", line 42, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:13d", line 623, in <module>
  File "f:13d", line 585, in version
  File "f:13d", line 558, in distribution
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Load network.lib.servers failed: Exception: No package metadata was found for importlib_metadata
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "network/lib/servers.py", line 13, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:15a", line 18, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:157", line 11, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:156", line 119, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:147", line 5, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:142", line 42, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Error loading package network.lib.servers (network/lib/servers.pyo pkg=False)
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "network/lib/servers.py", line 13, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:15a", line 18, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:157", line 11, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:156", line 119, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:147", line 5, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:142", line 42, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Load network.lib failed: Exception: No package metadata was found for importlib_metadata
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "network/lib/__init__.py", line 41, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "network/lib/servers.py", line 13, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:15a", line 18, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:157", line 11, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:156", line 119, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:147", line 5, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Error loading package network.lib (network/lib/__init__.pyo pkg=True)
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "network/lib/__init__.py", line 41, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "network/lib/servers.py", line 13, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:15a", line 18, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:157", line 11, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:156", line 119, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:147", line 5, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Load pupy.utils failed: Exception: No package metadata was found for importlib_metadata
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "pupy/utils.py", line 21, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "network/lib/__init__.py", line 41, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "network/lib/servers.py", line 13, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:15a", line 18, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:157", line 11, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:156", line 119, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
PackageNotFoundError: No package metadata was found for importlib_metadata

DEBUG:pupy:Error loading package pupy.utils (pupy/utils.pyo pkg=False)
Traceback (most recent call last):
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "pupy/utils.py", line 21, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "network/lib/__init__.py", line 41, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "network/lib/servers.py", line 13, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:15a", line 18, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:157", line 11, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:156", line 119, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
PackageNotFoundError: No package metadata was found for importlib_metadata

Traceback (most recent call last):
  File "pupy/__init__.py", line 316, in loadpy
  File "f:15a", line 18, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:157", line 11, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:156", line 119, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:147", line 5, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:142", line 42, in <module>
  File "pupy/__init__.py", line 463, in load_module
  File "pupy/__init__.py", line 316, in loadpy
  File "f:13d", line 623, in <module>
  File "f:13d", line 585, in version
  File "f:13d", line 558, in distribution
  File "f:13d", line 215, in from_name
importlib_metadata.PackageNotFoundError: No package metadata was found for importlib_metadata
Exception KeyError: KeyError(4488,) in <module 'threading' from 'pupy://threading.pyo'> ignored
```
</details>

**Comment by alxchk** [comment]
Yes, this because of updated netaddr. Try to pull and rebuild templates.

**Comment by xView60** [comment]
how do we rebuild templates?

**Comment by Avatat** [comment]
> how do we rebuild templates?

As I remember, the build procedure is described here: https://github.com/n1nj4sec/pupy/wiki/Installation#docker But still, it didn't work after building.
Finally, I used this project: https://github.com/nathanlopez/Stitch to the job.

**Comment by s1st3r** [comment]
Actually i noticed there are a lot of code errors on the C code for the main windows payload.

There is a lot of work to be done there.
