### ISSUE TITLE
Failing to create a work space with -NC flag

### ISSUE THREAD

**Issue by reecep55** [n1nj4sec/pupy#864]
On a separate VM created last week python create-workspace.py -NC -E docker pupyws could create a workspace with no issue

The following is now outputted when trying to create a workspace on a more recent installation of pupy:

python create-workspace.py -NC -E docker pupyws
...
...
Step 8/12 : RUN 	apt-get remove -y 		autoconf automake libssl1.0-dev libffi-dev python-dev 		libtool build-essential && apt-get -y autoremove && 		rm -rf /root/.cache /build
 ---> Using cache
 ---> da63048fb623
Step 9/12 : ADD 	https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20200519/mimikatz_trunk.zip 		/opt/mimikatz
ADD failed: failed to GET https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20200519/mimikatz_trunk.zip with status 404 Not Found: Not Found
Traceback (most recent call last):
  File "create-workspace.py", line 653, in <module>
    main()
  File "create-workspace.py", line 571, in main
    args.network, templates, args.squash
  File "create-workspace.py", line 397, in create_container_env
    subprocess.check_call(build_command, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', u'build', u'-t', u'pupy-python2-env', u'-f', u'/home/rp/pupy/pupy/conf/Dockerfile.env', u'/home/rp/pupy/pupy']' returned non-zero exit status 1

Is create workspace failing when the GET request for mimikatz fails?

**Comment by alxchk** [comment]
Looks like there was new release of mimikatz, URI was outdated and needs to be updated

**Comment by reecep55** [comment]
Do you know where that URL is located in the code so I can update it to the newest release? I couldn't find it in create-workspace.py or locate what's being run in that section of the installation.

**Comment by alxchk** [comment]
Just pushed updated url

**Comment by reecep55** [comment]
Awesome, can create a workspace without -NC flag now. Thanks for updating
