### ISSUE TITLE
Error with requirements.txt

### ISSUE THREAD

**Issue by NTHN1** [n1nj4sec/pupy#890]
root@KALINUX:~/pupy/pupy# pip install -r requirements.txt

Collecting https://github.com/alxchk/tinyec/archive/master.zip (from -r requirements.txt (line 8))
  Using cached https://github.com/alxchk/tinyec/archive/master.zip
Collecting https://github.com/benoitc/http-parser/archive/master.zip (from -r requirements.txt (line 19))
  Using cached https://github.com/benoitc/http-parser/archive/master.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting https://github.com/AlessandroZ/pypykatz/archive/master.zip (from -r requirements.txt (line 23))
  Using cached https://github.com/AlessandroZ/pypykatz/archive/master.zip
Collecting https://github.com/warner/python-ed25519/archive/master.zip (from -r requirements.txt (line 24))
  Using cached https://github.com/warner/python-ed25519/archive/master.zip
Collecting https://github.com/alxchk/urllib-auth/archive/master.zip (from -r requirements.txt (line 45))
  Using cached https://github.com/alxchk/urllib-auth/archive/master.zip
Collecting https://github.com/alxchk/pykcp/archive/master.zip (from -r requirements.txt (line 46))
  Using cached https://github.com/alxchk/pykcp/archive/master.zip
Collecting pycryptodome
  Using cached pycryptodome-3.9.9-cp39-cp39-manylinux1_x86_64.whl (13.7 MB)
Requirement already satisfied: pefile in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (2019.4.18)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (5.3.1)
Collecting rsa
  Using cached rsa-4.7-py3-none-any.whl (34 kB)
Requirement already satisfied: netaddr in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (0.7.19)
Collecting ecdsa==0.13
  Using cached ecdsa-0.13-py2.py3-none-any.whl (86 kB)
Collecting paramiko==2.0.2
  Using cached paramiko-2.0.2-py2.py3-none-any.whl (171 kB)
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (from -r requirements.txt (line 9)) (5.8.0)
Collecting netifaces
  Using cached netifaces-0.10.9.tar.gz (28 kB)
Collecting pylzma
  Using cached pylzma-0.5.0.tar.gz (4.2 MB)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from -r requirements.txt (line 12)) (0.4.4)
Collecting mss==4.0.3
  Using cached mss-4.0.3-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: pyOpenSSL in /usr/lib/python3/dist-packages (from -r requirements.txt (line 14)) (19.1.0)
Requirement already satisfied: scapy in /usr/lib/python3/dist-packages (from -r requirements.txt (line 15)) (2.4.4)
Requirement already satisfied: impacket in /usr/lib/python3/dist-packages (from -r requirements.txt (line 16)) (0.9.22)
Collecting pyuv
  Using cached pyuv-1.4.0.tar.gz (400 kB)
Requirement already satisfied: dnslib in /usr/lib/python3/dist-packages (from -r requirements.txt (line 18)) (0.9.14)
Collecting cerberus
  Using cached Cerberus-1.3.2.tar.gz (52 kB)
Collecting logutils
  Using cached logutils-0.3.5.tar.gz (27 kB)
Collecting secretstorage==2.3.1
  Using cached SecretStorage-2.3.1.tar.gz (16 kB)
Requirement already satisfied: pygments in /usr/lib/python3/dist-packages (from -r requirements.txt (line 25)) (2.7.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 26)) (2.24.0)
Collecting tornado==v5.1.1
  Using cached tornado-5.1.1.tar.gz (516 kB)
Collecting poster
  Using cached poster-0.8.1.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4_ay3g6t/poster/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4_ay3g6t/poster/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_03ob06p
         cwd: /tmp/pip-install-4_ay3g6t/poster/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4_ay3g6t/poster/setup.py", line 2, in <module>
        import poster
      File "/tmp/pip-install-4_ay3g6t/poster/poster/__init__.py", line 29, in <module>
        import poster.streaminghttp
      File "/tmp/pip-install-4_ay3g6t/poster/poster/streaminghttp.py", line 61
        print "send:", repr(value)
              ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Ezioz** [comment]
me too

**Comment by Ezioz** [comment]
> me too

python2
