### ISSUE TITLE
Mimikatz Version 2.2.0-20200816 in Dockerfile.env and Dockerfile.default does not exist anymore

### ISSUE THREAD

**Issue by Guillaume-Muller** [n1nj4sec/pupy#904]
When trying to build the Docker Images, we face an error when downloading Mimikatz_trunk :  The "2.2.0-20200816" release is not avalaible on GitHub anymore.

The lastest avalaible release is : https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20210709/mimikatz_trunk.zip

**Comment by Lengso** [comment]
```
Removing intermediate container 8aaea9c6a688
 ---> 0f4b5f7f1cac
Step 9/12 : ADD         https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20200816/mimikatz_trunk.zip              /opt/mimikatz
ADD failed: failed to GET https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20200816/mimikatz_trunk.zip with status 404 Not Found: Not Found
Traceback (most recent call last):
  File "create-workspace.py", line 653, in <module>
    main()
  File "create-workspace.py", line 571, in main
    args.network, templates, args.squash
  File "create-workspace.py", line 397, in create_container_env
    subprocess.check_call(build_command, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', u'build', u'-t', u'pupy-python2-env', u'-f', u'/root/pupy/pupy/conf/Dockerfile.env', u'/root/pupy/pupy']' returned non-zero exit status 1

```

When can it be repaired, the build is unsuccessful

**Comment by Lengso** [comment]
```
root@Pupy:~/pupy# grep -r 'https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20200816/mimikatz_trunk.zip'
pupy/conf/Dockerfile.env:       https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20200816/mimikatz_trunk.zip \
pupy/conf/Dockerfile.default:ADD https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20200816/mimikatz_trunk.zip \

```

Change link: https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20210810-2/mimikatz_trunk.zip, successfully built
